In [3]:
from scipy.io import loadmat
images = loadmat('/home/workspace/keras-person-search/data/psdb/dataset/annotation/Images.mat')
person = loadmat('/home/workspace/keras-person-search/data/psdb/dataset/annotation/Person.mat')
pool = loadmat('/home/workspace/keras-person-search/data/psdb/dataset/annotation/pool.mat')
occlusion = loadmat('/home/workspace/keras-person-search/data/psdb/dataset/annotation/test/subset/Occlusion.mat')
resolution = loadmat('/home/workspace/keras-person-search/data/psdb/dataset/annotation/test/subset/Resolution.mat')

In [33]:
pool['pool'][3]

array([array(['s15538.jpg'],
      dtype='<U10')], dtype=object)

In [23]:
for node in person['Person'][0][100]:
    print(node)

['p101']
[[2]]
[[ (array(['s197.jpg'],
      dtype='<U8'), array([[380, 255,  98, 238]], dtype=uint16), array([[0]], dtype=uint8))
  (array(['s198.jpg'],
      dtype='<U8'), array([[351, 326,  90, 226]], dtype=uint16), array([[0]], dtype=uint8))]]


In [42]:
for node in images['Img'][0]:
    if 's12631.jpg' == node[0]:
        print(node)

(array(['s12631.jpg'],
      dtype='<U10'), array([[1]], dtype=uint8), array([[(array([[389, 167,  49, 119]], dtype=uint16), array([[0]], dtype=uint8))]],
      dtype=[('idlocate', 'O'), ('ishard', 'O')]))


In [85]:
person['Person'][0][0]

(array(['p1'],
      dtype='<U2'), array([[3]], dtype=uint8), array([[ (array(['s1.jpg'],
      dtype='<U6'), array([[391, 243,  37, 112]], dtype=uint16), array([[0]], dtype=uint8)),
        (array(['s2.jpg'],
      dtype='<U6'), array([[195, 274,  51, 142]], dtype=uint16), array([[1]], dtype=uint8)),
        (array(['s3.jpg'],
      dtype='<U6'), array([[250, 241,  92, 247]], dtype=uint8), array([[0]], dtype=uint8))]],
      dtype=[('imname', 'O'), ('idlocate', 'O'), ('ishard', 'O')]))

In [77]:
for i,v in enumerate(person['Person'][0]):
    for n in v[2][0]:
        print(n[1])

[[391 243  37 112]]
[[195 274  51 142]]
[[250 241  92 247]]
[[426 249  42 118]]
[[204 278  55 148]]
[[303 261  95 253]]
[[306 269  98 218]]
[[140 284 183 371]]
[[ 59 224 172 331]]
[[ 34 446 138 353]]
[[190 306  66 176]]
[[181 421  51 153]]
[[297 303  83 253]]
[[305 248  73 220]]
[[259 383  45 120]]
[[358 321  72 192]]
[[301 381  45 120]]
[[283 319  70 186]]
[[342 369  50 134]]
[[208 308  70 187]]
[[162 308  87 223]]
[[257 339  49 111]]
[[374 333  48 129]]
[[214 313  80 215]]
[[231 315 110 295]]
[[283 341  69 184]]
[[301 303 168 493]]
[[318 354  75 220]]
[[160 293 153 377]]
[[266 300  98 262]]
[[243  96  61 163]]
[[303 277 160 377]]
[[285 373  79 191]]
[[212 387 154 349]]
[[320 257 129 344]]
[[386 260  86 231]]
[[117 268 179 392]]
[[279 292  43 119]]
[[318 281  68 210]]
[[328 301 157 369]]
[[323 312  36  96]]
[[196 334  61 163]]
[[308 291  78 178]]
[[338 259  55 148]]
[[174 186  76 203]]
[[272 217 119 319]]
[[272 166  76 226]]
[[320 164  86 280]]
[[167 104  87 233]]
[[253 260 114 304]]


[[113  17 148 442]]
[[225  92 123 371]]
[[184  70 128 376]]
[[251  65 110 319]]
[[117  63 108 370]]
[[134  65 117 312]]
[[293  51 161 430]]
[[203  36 291 729]]
[[216  56 131 376]]
[[156  68 139 373]]
[[148  42 175 469]]
[[246  85 136 363]]
[[234  60 142 373]]
[[298  89 115 308]]
[[363  74 186 517]]
[[164 125 144 383]]
[[116  80 132 371]]
[[137  38 168 480]]
[[169   9 231 653]]
[[261 116 123 328]]
[[140 126 106 297]]
[[361  97 123 359]]
[[267  68 100 312]]
[[  1 132 113 333]]
[[227 111 150 432]]
[[378  76 128 375]]
[[141 101 131 374]]
[[198  68 139 403]]
[[134  31 188 550]]
[[130   2 217 580]]
[[131  17 212 567]]
[[262  84 170 454]]
[[222  45 173 527]]
[[288  98 180 549]]
[[280  86 181 484]]
[[148 298 112 312]]
[[195 362 128 349]]
[[175  76 120 343]]
[[175  61 184 490]]
[[264  26 199 530]]
[[263  34 163 465]]
[[104  30 190 485]]
[[ 73  17 235 624]]
[[100   2 206 550]]
[[284  42 170 487]]
[[251  82 234 655]]
[[116  36 242 647]]
[[145 118 145 387]]
[[119  10 213 615]]
[[383   1 192 533]]


[[513 131  84 295]]
[[365 231 118 315]]
[[109 240 189 490]]
[[271 216 144 356]]
[[212 196 108 271]]
[[139 199 124 331]]
[[160  32 162 435]]
[[275  29 151 451]]
[[357  73 133 356]]
[[155  65 135 375]]
[[273  72 130 348]]
[[157  65 142 402]]
[[ 16 109 127 343]]
[[477  74 121 460]]
[[ 81 114 101 294]]
[[356  84 132 432]]
[[228  54 158 421]]
[[236 130 120 327]]
[[331  42  86 242]]
[[226  72  73 201]]
[[198  64  68 181]]
[[502  45  71 195]]
[[505  32  92 310]]
[[377   4 121 392]]
[[213  50 148 424]]
[[460  21  88 318]]
[[372   5 201 602]]
[[293  28  99 266]]
[[181  45 133 356]]
[[181  45 133 356]]
[[258 237  88 237]]
[[126 230  75 194]]
[[285 109 115 277]]
[[204 121  57 164]]
[[246 180  65 223]]
[[112 137  57 176]]
[[262 137  89 237]]
[[337 185  75 208]]
[[207 137 150 340]]
[[245 179  55 170]]
[[235 194  57 160]]
[[479 228  90 228]]
[[251 192  50 154]]
[[335 162 100 319]]
[[148 276  71 189]]
[[256 283  51 150]]
[[181 269  67 148]]
[[111 248 199 500]]
[[302 338  81 196]]
[[425 251  51 162]]


[[293 466  35  95]]
[[157 361  45 120]]
[[115 400  40 106]]
[[312 363  32  86]]
[[280 377  50 134]]
[[195 480  69 185]]
[[ 68 504  70 187]]
[[224 337  53 141]]
[[169 422  64 171]]
[[150 433  55 147]]
[[225 387  27  73]]
[[227 421  26  72]]
[[279 415  46 123]]
[[162 420  64 173]]
[[198 432  50 135]]
[[210 424  69 184]]
[[213 354  45 120]]
[[ 49 357  25  66]]
[[233 385  29  77]]
[[261 411  33  89]]
[[362 449  38 101]]
[[130 465  42 113]]
[[195 459  36  96]]
[[232 467  29  77]]
[[329 456  26  70]]
[[296 449  44 119]]
[[301 463  45 120]]
[[153 486  35  95]]
[[ 85 472  37 100]]
[[219 451  44 119]]
[[354 462  32  87]]
[[270 493  36  98]]
[[247 480  33  90]]
[[325 420  31  83]]
[[290 446  34  91]]
[[311 445  34  91]]
[[339 475  34  93]]
[[145 420  35  95]]
[[109 447  37 100]]
[[113 446  39 104]]
[[122 480  40 106]]
[[ 75 431  40 107]]
[[310 448  38 102]]
[[195 435  33  90]]
[[217 460  32  87]]
[[172 425  37  99]]
[[183 450  36  98]]
[[187 410  31  85]]
[[210 378  17  46]]
[[258 452  29  78]]


[[156 339  22  60]]
[[111 354  21  58]]
[[ 41 349  21  58]]
[[ 93 372  15  42]]
[[ 25 372  14  38]]
[[159 327  16  45]]
[[148 341  23  63]]
[[122 373  33  89]]
[[137 395  47 126]]
[[ 29 426  76 204]]
[[176 321  17  45]]
[[178 338  21  58]]
[[176 361  30  81]]
[[230 378  43 115]]
[[229 406  68 182]]
[[ 70 377  27  73]]
[[ 82 397  36  98]]
[[247 341  20  53]]
[[378 335  30  80]]
[[210 332  32  86]]
[[146 345  33  89]]
[[ 56 361  37 100]]
[[193 352  22  60]]
[[134 361  24  65]]
[[213 318  40 107]]
[[132 325  43 114]]
[[195 285  15  40]]
[[ 55 367  32  86]]
[[204 297  39 104]]
[[181 304  30  81]]
[[174 274  25  69]]
[[164 304  32  87]]
[[147 296  45 122]]
[[224 324  44 118]]
[[176 334  38 102]]
[[183 322  41 110]]
[[237 280  40 106]]
[[229 328  43 114]]
[[188 321  46 124]]
[[229 287  62 167]]
[[285 328  92 248]]
[[222 271  13  36]]
[[192 299  19  51]]
[[174 319  28  76]]
[[123 370  50 134]]
[[118 223 107 286]]
[[238 269  61 164]]
[[ 99 241  61 165]]
[[ 63 230  96 257]]
[[144 198 150 402]]


[[441 200  57 162]]
[[256 199  58 155]]
[[198 187  86 231]]
[[486 242  88 237]]
[[558 209  53 143]]
[[421 208  54 145]]
[[362 198  70 187]]
[[446 167  61 179]]
[[519 114  53 143]]
[[206 186 104 279]]
[[ 74 127 170 471]]
[[366 184  60 160]]
[[382 120  79 212]]
[[566 190 160 408]]
[[210 151 140 400]]
[[546  64  95 267]]
[[247  89 125 350]]
[[341 186  70 215]]
[[434  68  87 233]]
[[400 136 158 440]]
[[160  78 111 297]]
[[341  45 153 439]]
[[385  71 129 344]]
[[316 122 102 283]]
[[327  91 127 363]]
[[282  95 168 503]]
[[138 101 139 372]]
[[679 135 105 280]]
[[143 160  96 257]]
[[235 120 106 296]]
[[ 86  60 148 441]]
[[404 103  89 237]]
[[578  35 124 351]]
[[506 121  65 173]]
[[670  68  81 232]]
[[396 137 111 356]]
[[273 167  67 180]]
[[536 163  71 189]]
[[475 189  89 246]]
[[343 166  87 233]]
[[235 225  66 168]]
[[420 181  51 144]]
[[490 234  59 159]]
[[395 199  67 179]]
[[410 186  62 167]]
[[403 157 119 317]]
[[512 131 135 361]]
[[271 202  34  91]]
[[159 149 157 419]]
[[497 188  86 229]]


[[262 190 158 463]]
[[381 244  75 200]]
[[189 170  84 250]]
[[266 207  94 266]]
[[158 175  73 195]]
[[237 154  83 247]]
[[261 135  87 275]]
[[220 110  88 235]]
[[226  93 100 269]]
[[115 140 127 339]]
[[141 158  74 219]]
[[241 161  73 194]]
[[372 130  64 184]]
[[305 124  57 171]]
[[118 122  46 135]]
[[ 58 109  57 152]]
[[ 18 128 129 378]]
[[323 228  62 181]]
[[248 219  76 225]]
[[  1 219  80 215]]
[[  1 203 127 341]]
[[115 217  48 149]]
[[147 193  91 274]]
[[ 15 182  82 220]]
[[441 194 142 395]]
[[397 215  49 131]]
[[256 200  52 149]]
[[223  60 114 306]]
[[235  89 103 277]]
[[150 165  65 175]]
[[200 142  86 229]]
[[138  71 165 442]]
[[180 150 125 335]]
[[296 162  70 185]]
[[239 138  94 253]]
[[406 132 121 329]]
[[ 50  82 140 393]]
[[150  23 203 538]]
[[211  75 162 435]]
[[197 244  72 206]]
[[512 145  62 166]]
[[274 255  49 154]]
[[205 150 116 330]]
[[426 110 172 628]]
[[334 114 103 275]]
[[268 143  88 272]]
[[147 109 136 385]]
[[215  86 126 368]]
[[ 16 155  79 219]]
[[ 86 104 105 302]]


[[625 105  66 177]]
[[662 174  92 280]]
[[394  49  58 185]]
[[306 122  86 252]]
[[404 155  59 177]]
[[238 165  34  92]]
[[ 82 159  44 117]]
[[321 177  52 153]]
[[366 149  73 195]]
[[250 201  89 237]]
[[ 47 183  28  86]]
[[190 126  72 192]]
[[ 70 192  24  73]]
[[255 149  59 170]]
[[347 163  61 185]]
[[325 182  63 198]]
[[371 159  55 172]]
[[319 152  59 178]]
[[259 119  59 180]]
[[ 96 174  70 206]]
[[685 211  48 129]]
[[ 88 187  57 173]]
[[466 172  53 164]]
[[443 152  80 232]]
[[687 151 104 293]]
[[429 116 137 397]]
[[284 158  46 125]]
[[324 120  58 163]]
[[241 166  35  93]]
[[162 122 108 289]]
[[103  84 120 318]]
[[147  45 148 439]]
[[292 119  90 254]]
[[330 157  76 240]]
[[551 114  95 306]]
[[484 108  91 250]]
[[460 187  60 160]]
[[389  96  85 246]]
[[409 176  59 174]]
[[573 106  57 167]]
[[145 155  38 108]]
[[285 180  34  91]]
[[378 132  72 202]]
[[497 142 109 292]]
[[229 117 108 288]]
[[299 151  79 228]]
[[282 157  61 184]]
[[347 178  88 236]]
[[366 181  67 178]]
[[ 97 149  50 134]]


[[217 182 105 298]]
[[203 220 106 336]]
[[208 109 207 553]]
[[277 236 100 273]]
[[216 189  37 112]]
[[204 124  65 194]]
[[240 177  67 214]]
[[251 257  47 151]]
[[210 283  35 109]]
[[227 366  42 114]]
[[180 176  44 120]]
[[289 161  78 243]]
[[270 245  60 171]]
[[148 273  47 125]]
[[136 355  47 127]]
[[296 223  41 112]]
[[263 246  54 145]]
[[283 213  59 159]]
[[272 236  45 120]]
[[271 184  58 158]]
[[266 192  60 164]]
[[296 259  45 126]]
[[338 291  44 119]]
[[271 169  94 285]]
[[256 232  85 249]]
[[222 293  42 113]]
[[278 299  31  94]]
[[422 199  54 160]]
[[125 312  41 112]]
[[373 145 103 277]]
[[150 254 105 282]]
[[279 288  74 178]]
[[242 254  47 112]]
[[263 227  63 174]]
[[194  93 109 319]]
[[282 158  60 176]]
[[194 242  58 175]]
[[194  50 122 365]]
[[315  75 114 304]]
[[337 142  57 153]]
[[123 201  55 160]]
[[229 209  48 128]]
[[385 212  53 142]]
[[207 231  51 140]]
[[285 221  59 174]]
[[303 217  55 148]]
[[158 229  57 152]]
[[327 236  47 136]]
[[314 146  59 158]]
[[246 244  92 255]]


[[625 137 125 336]]
[[557  83 112 300]]
[[343 176  49 132]]
[[466  15 184 492]]
[[167  90  97 259]]
[[284 184  53 144]]
[[176  65  97 260]]
[[395  37  99 264]]
[[264  90  96 256]]
[[457  63  90 242]]
[[362 106  93 249]]
[[264 143  43 116]]
[[419 114  89 240]]
[[236 144  44 117]]
[[112   1 140 374]]
[[484  56 124 330]]
[[273  39 120 322]]
[[401  94 115 309]]
[[258  89  73 196]]
[[303 104 126 336]]
[[340  96  75 201]]
[[182 112 129 346]]
[[444 138  79 212]]
[[368   8 117 312]]
[[195 152  44 124]]
[[525 139  83 223]]
[[502  15 111 297]]
[[154 162  38 104]]
[[611 146  84 224]]
[[606  14 125 356]]
[[214 142  78 209]]
[[516 114 101 272]]
[[399  69 130 347]]
[[481 139 132 354]]
[[512 172  86 231]]
[[612 236  83 221]]
[[263  98  61 162]]
[[166 161 104 278]]
[[409 190  75 201]]
[[324 108  54 145]]
[[266 168 102 274]]
[[351 194  75 202]]
[[213  67 153 411]]
[[445 212  41 123]]
[[354  32 141 376]]
[[360 196  43 116]]
[[447  82 123 329]]
[[337 208  40 108]]
[[192 153  94 253]]
[[458 112 112 300]]


[[131  44  99 264]]
[[305  88  58 156]]
[[137 106 131 350]]
[[467 177  39 105]]
[[368 104  56 151]]
[[485 181  89 240]]
[[520 194  26  72]]
[[401  75  63 170]]
[[ 92 128 100 329]]
[[442 181  36  96]]
[[451 207  55 148]]
[[573 108  49 132]]
[[578 209  56 150]]
[[394 126  39 106]]
[[579  19 105 281]]
[[527 189  76 205]]
[[601 196  53 144]]
[[296 195  38 102]]
[[701 141  77 206]]
[[252 148  62 167]]
[[637 122 160 444]]
[[128  55 162 432]]
[[222 200 100 269]]
[[399 224  85 227]]
[[600 332  57 154]]
[[396 236  47 127]]
[[387 269  49 132]]
[[454 112 112 300]]
[[479 200  68 182]]
[[502 232  54 146]]
[[348 204  31  85]]
[[138 258  51 137]]
[[149 227  46 124]]
[[321 282  27  75]]
[[317 281  28  77]]
[[497 250  39 105]]
[[453 249  39 105]]
[[262 275  48 130]]
[[ 92 209  45 121]]
[[325 177  54 146]]
[[571 218  54 145]]
[[144 174  58 155]]
[[427 224  47 126]]
[[505  72 150 402]]
[[193 187  63 169]]
[[273 150  62 165]]
[[284 217  54 146]]
[[593 165  66 176]]
[[231 224  55 147]]
[[284 106 118 316]]


[[197 198  74 199]]
[[165 188  51 138]]
[[522 179  89 247]]
[[261 421  39 106]]
[[ 41 291  76 205]]
[[122 415  44 118]]
[[346 149  90 241]]
[[161 419  43 117]]
[[255 160  88 236]]
[[ 60 404  72 194]]
[[237 162  26  71]]
[[229   1 166 443]]
[[331 178  64 173]]
[[539 119  55 148]]
[[463 270  98 262]]
[[609  43 118 315]]
[[178 180  90 241]]
[[269 282  43 115]]
[[577 269  50 135]]
[[385 288  39 104]]
[[ 84 278  35  95]]
[[628 266  25  68]]
[[714 130  31  84]]
[[557 266  18  49]]
[[599 131  26  70]]
[[446  75  86 242]]
[[180 147 137 390]]
[[402  92  70 202]]
[[321 164 103 314]]
[[226  48 146 493]]
[[ 78 131 225 668]]
[[ 23 167 104 278]]
[[ 48  97 164 453]]
[[161 182 155 414]]
[[103 114 148 444]]
[[490 103  85 234]]
[[281 173 121 348]]
[[303  91 101 272]]
[[124 167 115 318]]
[[270 116  53 172]]
[[457 192  75 202]]
[[213 124  49 132]]
[[542 114  49 132]]
[[340   1 202 550]]
[[412 165  71 191]]
[[347 196  39 113]]
[[247 180  46 134]]
[[209 250  72 207]]
[[315 229  73 202]]
[[118 143  71 223]]


[[246 134 136 406]]
[[295 181 166 534]]
[[348  35  57 159]]
[[480 194  61 146]]
[[295 214  53 150]]
[[531 114  67 196]]
[[425  80  42 121]]
[[317 128  69 186]]
[[321 124  96 300]]
[[227  69  30  80]]
[[498 109  44 118]]
[[121 125  64 171]]
[[116 145  75 167]]
[[191 111  87 233]]
[[323  59  62 181]]
[[394  84  65 174]]
[[387 130  37 100]]
[[451 154  36  97]]
[[182  56 220 715]]
[[  1   1 152 543]]
[[158  72 129 384]]
[[402 176  29  79]]
[[379 117  41 109]]
[[352 116  52 139]]
[[236  62 187 545]]
[[ 86  41 193 562]]
[[125  14 276 738]]
[[284 156  35  94]]
[[257 149  85 228]]
[[279 168  58 154]]
[[180 133  50 131]]
[[258 166  30  82]]
[[198 176  69 204]]
[[231 186  46 139]]
[[137 150  36 107]]
[[367 144  24  65]]
[[127 166  24  64]]
[[428 189  24  63]]
[[271 175  30  80]]
[[217 110  44 134]]
[[339 230  28  76]]
[[132 190  49 133]]
[[109  95 111 297]]
[[ 52 108 159 425]]
[[310 114  45 146]]
[[140 160  61 198]]
[[269 101  86 265]]
[[255 118  47 144]]
[[ 41 172  74 198]]
[[148 120  87 263]]


[[127 234  69 186]]
[[158 233  47 126]]
[[172 240  73 195]]
[[335 213  73 214]]
[[370 205  70 203]]
[[303 257  41 106]]
[[ 49 253  50 133]]
[[411 220  54 159]]
[[247 190  62 184]]
[[301 193  62 166]]
[[185 175  69 185]]
[[230 184  56 166]]
[[135 190  62 180]]
[[186 203  52 159]]
[[  1 184  86 237]]
[[383 141  86 258]]
[[471 161  85 240]]
[[266 196  64 188]]
[[379 190  57 170]]
[[173 188  75 200]]
[[301 189  65 194]]
[[ 16 208  65 174]]
[[204 218  55 148]]
[[384 232  58 178]]
[[376 177  70 204]]
[[ 75 225  67 198]]
[[298 209  62 184]]
[[342 237  63 189]]
[[257 193  65 194]]
[[244 226  74 197]]
[[144 178  77 210]]
[[190 182 125 334]]
[[ 90 151 140 397]]
[[199 237  68 182]]
[[ 86 247  61 172]]
[[248 201  94 281]]
[[192 151 136 363]]
[[349 192  64 173]]
[[385 221  69 184]]
[[284 182  67 180]]
[[255 251  59 181]]
[[171 150  81 237]]
[[123 216  76 204]]
[[ 63 269  48 128]]
[[473 215  42 124]]
[[  8 235  54 143]]
[[249 250  43 115]]
[[273 244  44 118]]
[[199 271  36 100]]
[[422 237  40 115]]


[[190 310  30  77]]
[[500 244  30  82]]
[[257 134  37 100]]
[[256 319  38 102]]
[[449 226  40 108]]
[[148 210  30  80]]
[[ 55 203  28  75]]
[[205 455  39 106]]
[[224 191  54 144]]
[[171 177  51 137]]
[[ 40 176  44 119]]
[[373 545  61 164]]
[[282 187  51 138]]
[[223 172  50 135]]
[[112 161  43 117]]
[[187 428  72 194]]
[[128 481  77 206]]
[[252 373  83 222]]
[[280 439  66 177]]
[[187 496  71 190]]
[[264 417  85 228]]
[[278 195  46 123]]
[[481 203  50 135]]
[[233 238  37  99]]
[[157  96  36  97]]
[[221 183  33  90]]
[[268  76  36  97]]
[[181 220  71 190]]
[[ 68 197 107 285]]
[[361 188  91 271]]
[[265 227  73 197]]
[[264 142 127 340]]
[[ 67 164 124 331]]
[[ 74 147 123 350]]
[[ 10 211  73 196]]
[[236 202  80 215]]
[[159 168 102 312]]
[[ 34  66 196 522]]
[[220 163  99 265]]
[[186 158  95 255]]
[[278 142  90 242]]
[[506 135 101 261]]
[[326 137 132 354]]
[[446 200  27  74]]
[[511 134  32  86]]
[[409 190  69 194]]
[[503 138  59 157]]
[[445 140  68 182]]
[[405 164  69 190]]
[[388 239  31  91]]


[[481 265  31  94]]
[[ 94 255  61 163]]
[[114 224  52 154]]
[[398 260  35 108]]
[[141 297  63 155]]
[[276 184  54 145]]
[[150 238  45 120]]
[[399 145  42  98]]
[[435 243  59 158]]
[[168 163  81 215]]
[[191 229  59 159]]
[[117 116  68 182]]
[[ 37 182  84 190]]
[[159 155  74 191]]
[[112 173  51 140]]
[[127 143  29  78]]
[[468 110  51 117]]
[[466 176  62 127]]
[[534 156  66 178]]
[[ 64 152  30  82]]
[[190 156  60 136]]
[[494 117  50 103]]
[[128 101  83 197]]
[[244 169  63 169]]
[[213 164  42 113]]
[[110  48  47 127]]
[[166  45  86 230]]
[[327 125  63 170]]
[[173  59  42 113]]
[[274  71  69 186]]
[[292 135  47 151]]
[[214  82  34  93]]
[[265 166  41 111]]
[[289  51  42 120]]
[[111 100  76 205]]
[[195  83  41 110]]
[[182  83  56 150]]
[[253  74  73 195]]
[[194  62  50 135]]
[[401  69  40 108]]
[[114  86  37 101]]
[[ 69  89  52 140]]
[[101  71  74 197]]
[[239  57  53 163]]
[[483  72  42 112]]
[[285  52  52 145]]
[[519  67  40 107]]
[[464  76  58 129]]
[[289  38  72 204]]
[[111  43  41 110]]


[[245 194  42 122]]
[[399 114 108 289]]
[[641  44 139 403]]
[[474  92 145 355]]
[[ 55  65  97 259]]
[[452  50 141 400]]
[[332 129  79 238]]
[[150 120 119 317]]
[[277 112 112 334]]
[[320  59 123 377]]
[[535  87 119 361]]
[[237 130 118 317]]
[[425 130 119 319]]
[[457 110 115 339]]
[[ 83  90 140 358]]
[[626  87 119 362]]
[[489 177  76 204]]
[[465 213  62 167]]
[[393 172  74 203]]
[[539 209  75 187]]
[[453 108 112 341]]
[[325 117  96 292]]
[[350  60 129 390]]
[[224  81 138 368]]
[[460 159 100 290]]
[[482  72  81 241]]
[[512 110  80 257]]
[[121  89  68 197]]
[[346 103  82 219]]
[[259 148  79 254]]
[[184 104  64 191]]
[[397  89 106 317]]
[[207 114 106 304]]
[[202  22 129 426]]
[[565  29 151 417]]
[[194 110  91 267]]
[[486 124  66 204]]
[[442  58 110 360]]
[[158  84 150 364]]
[[267  95 133 355]]
[[358 137  96 276]]
[[336 145  84 225]]
[[544  47 150 401]]
[[239 174  85 227]]
[[351 107 147 341]]
[[190  84 150 366]]
[[258  88 144 360]]
[[416  70 109 332]]
[[412 203  91 243]]
[[478   1 165 440]]


[[ 76 301 147 394]]
[[ 82 218 137 367]]
[[  8 342 176 456]]
[[116 262 151 403]]
[[120 250 116 370]]
[[146 252 117 314]]
[[194 285  99 264]]
[[243 311  89 238]]
[[336 272 130 347]]
[[390 279 125 335]]
[[321 260 138 369]]
[[142 232 199 532]]
[[143 146  99 265]]
[[264 230 128 343]]
[[ 40 157 189 505]]
[[ 70 230 159 426]]
[[265 313  76 203]]
[[412 258 100 268]]
[[330 209 117 312]]
[[425  77 127 368]]
[[187 204  98 263]]
[[213 282 106 283]]
[[107 121  78 210]]
[[272 142  84 224]]
[[239  94  83 223]]
[[391  75 100 266]]
[[ 97  96 237 633]]
[[110 328 159 425]]
[[371  67 111 275]]
[[208 189  92 250]]
[[341 275 126 338]]
[[110 294 115 301]]
[[194 323 166 445]]
[[322 294 138 367]]
[[362 251 141 377]]
[[296  59 192 435]]
[[290 199 142 380]]
[[293 216 154 411]]
[[331 308 146 389]]
[[269 190 170 455]]
[[379 161 126 337]]
[[270 355 113 257]]
[[457 297 136 398]]
[[391 173 101 318]]
[[300 451 121 323]]
[[ 40 349 133 269]]
[[250 295  82 220]]
[[359  93 143 411]]
[[450 447  92 247]]
[[480 268 113 433]]


[[122 170 164 440]]
[[100 133 162 446]]
[[233 211 126 359]]
[[201 251 142 438]]
[[367 161 117 341]]
[[328 199 137 406]]
[[116 237 140 417]]
[[212 111 143 446]]
[[225 122 194 521]]
[[312 149 181 533]]
[[216 342  84 225]]
[[431 162  93 250]]
[[125 262 141 377]]
[[328 346  47 127]]
[[394 328 124 330]]
[[265 331  66 177]]
[[414 345  47 127]]
[[351 331  49 131]]
[[208 346  58 154]]
[[471 312  84 209]]
[[311 343  62 165]]
[[336 281 124 330]]
[[259 348  80 232]]
[[121 227 108 289]]
[[212 222 126 416]]
[[337 165 151 485]]
[[349 161 133 437]]
[[270 285  98 251]]
[[202 264  66 183]]
[[ 34 290 113 303]]
[[149 256  40 107]]
[[ 35 150 185 547]]
[[100 224 134 329]]
[[133 265  85 228]]
[[301 252  94 242]]
[[386 277  84 224]]
[[ 85 287  83 190]]
[[158 263  76 204]]
[[364 275 172 505]]
[[ 27 227 176 471]]
[[382 231 131 351]]
[[ 75 247 136 362]]
[[236 273  84 226]]
[[264 248  96 256]]
[[298 259 122 298]]
[[360 280  83 209]]
[[ 87 342 128 374]]
[[337 346 170 454]]
[[333 313 114 308]]
[[478 350 104 278]]


[[139 158 113 301]]
[[ 61 229 149 397]]
[[251 219  79 211]]
[[354 196 109 293]]
[[227  83 163 436]]
[[ 58 199 107 287]]
[[231 185 110 295]]
[[ 44  36 172 460]]
[[495 150  96 258]]
[[121 167 111 297]]
[[320 216  70 187]]
[[280 189 116 311]]
[[  7 128 147 392]]
[[260 214  71 189]]
[[221 200  93 250]]
[[203 213  71 189]]
[[220 227  89 239]]
[[295 212  86 229]]
[[210 198 125 333]]
[[340 128 132 354]]
[[198 204  44 120]]
[[332 105 205 547]]
[[131 163 124 331]]
[[162 213  41 110]]
[[196 126 234 625]]
[[212 171 133 355]]
[[293 137  89 239]]
[[265 130  84 224]]
[[274 149  53 142]]
[[406 271  65 175]]
[[294 278  47 125]]
[[245 165  80 214]]
[[185 155  74 198]]
[[228 162  51 137]]
[[338 284  62 167]]
[[255 287  46 124]]
[[338 193  73 196]]
[[323 217 139 373]]
[[392 170  80 214]]
[[256 192 135 362]]
[[368 222  72 192]]
[[353 241  77 207]]
[[433 231  68 181]]
[[327 248  78 209]]
[[199 216  61 164]]
[[161 169  97 261]]
[[255 207  58 156]]
[[ 92 159 103 275]]
[[264 196  39 105]]
[[264 203  58 156]]


[[182 127 101 272]]
[[ 77 132 112 300]]
[[266 309  34  91]]
[[  9  87 131 349]]
[[316 317  64 171]]
[[228 345  42 112]]
[[349 187  61 162]]
[[332 140  50 135]]
[[150 345  49 133]]
[[188 120  77 207]]
[[394 176  69 184]]
[[294 125  53 149]]
[[499  70 100 408]]
[[ 16 141  73 195]]
[[ 82 179  77 206]]
[[134 171  70 187]]
[[285 168  74 198]]
[[374 162  76 203]]
[[362 164  61 164]]
[[167 147  52 140]]
[[ 41 156  82 220]]
[[156 157  69 185]]
[[262 168  51 137]]
[[267 155  73 195]]
[[301 162  57 153]]
[[282 143  60 161]]
[[ 61 109  76 203]]
[[ 44 109  81 218]]
[[ 72 113  75 200]]
[[ 99 100  59 159]]
[[352 139  61 164]]
[[225 110  77 207]]
[[264 109  77 207]]
[[243 121  59 158]]
[[155 107  42 114]]
[[110 111  69 184]]
[[129 110  75 201]]
[[154 112  65 175]]
[[242  99  53 141]]
[[386 103  39 105]]
[[368  64 103 275]]
[[262  36 113 303]]
[[242  75  76 205]]
[[142 173  40 108]]
[[262  34 113 302]]
[[348 109  41 111]]
[[194  91  52 141]]
[[351  92  82 219]]
[[304  71  97 259]]
[[292  91  69 184]]


[[384 374  64 172]]
[[ 87 301  57 153]]
[[249 174  35  93]]
[[ 95 258  29  79]]
[[256 321  33  89]]
[[429 276  54 145]]
[[196 349  47 133]]
[[405 258  33  90]]
[[356 285  39 105]]
[[389 210  36  98]]
[[231 299  20  54]]
[[336 221  36  98]]
[[197 303  27  73]]
[[290  89  38 103]]
[[387 195  64 171]]
[[199 280  78 208]]
[[257 102  36  98]]
[[246 237  69 184]]
[[335 155  79 212]]
[[243 224  95 254]]
[[492 446  33  90]]
[[454 357  34  93]]
[[383 179  21  56]]
[[362 198  24  65]]
[[342 175  20  54]]
[[340 170  23  63]]
[[314 178  20  55]]
[[286 196  25  67]]
[[241 355  32  87]]
[[233 325  30  81]]
[[282 367  31  85]]
[[294 342  25  69]]
[[285 146  14  39]]
[[329 144  21  56]]
[[414 157  31  85]]
[[326 282  22  59]]
[[328 265  24  64]]
[[259 237  26  72]]
[[361 299  19  52]]
[[393 270  20  55]]
[[324 212  26  71]]
[[380 271  22  59]]
[[363 230  22  60]]
[[196 210  27  74]]
[[343 283  19  52]]
[[346 264  21  57]]
[[241  71 101 272]]
[[210  74 138 366]]
[[195 140 122 327]]
[[291 162  66 176]]


[[ 43 242  88 314]]
[[229 372  87 219]]
[[221 215  74 224]]
[[404 374  49 125]]
[[379 212  56 125]]
[[313 337  57 125]]
[[237 411  56 128]]
[[219  41  51 139]]
[[ 84 168  59 134]]
[[223 283  46 126]]
[[301 295  49 130]]
[[ 55 328  52  87]]
[[197 440  46  81]]
[[  1 364  49  96]]
[[218 477  54 110]]
[[282 353  60 132]]
[[215 366  48 128]]
[[197 373  50 109]]
[[194 318  50 131]]
[[388 330  57 128]]
[[181 345  47 117]]
[[536 152  54 114]]
[[151 422  68 127]]
[[447 142  48 105]]
[[376 298  48 117]]
[[351 111  47 100]]
[[300 224  52 109]]
[[357 346  50 130]]
[[209 362  52 136]]
[[388 268  48 122]]
[[237 424  52 125]]
[[ 97 278  39  93]]
[[131 467  58 146]]
[[311 414  56 117]]
[[127 327  47 117]]
[[356 276  65 131]]
[[382 420  62 118]]
[[427 381  50 132]]
[[249 231  48 117]]
[[165 369  45 107]]
[[468 350  58 113]]
[[420 240  52 119]]
[[305 517  54 137]]
[[321 429  48 110]]
[[273 335  46 126]]
[[323 455  59 121]]
[[200 351  50 126]]
[[352 410  54 112]]
[[324 458  63 116]]
[[ 16 162  60 134]]


[[702 141  67 180]]
[[681 150  53 142]]
[[676 146  78 208]]
[[726 138  71 213]]
[[703 140  50 154]]
[[488 161  55 149]]
[[506 112 121 324]]
[[625 165  58 162]]
[[375 133 115 313]]
[[618 144  66 178]]
[[486  94 121 345]]
[[521 120 103 281]]
[[287  85 141 363]]
[[612 141  81 217]]
[[437 114 126 336]]
[[ 76  90 133 356]]
[[678 136  62 167]]
[[571  87 128 343]]
[[646 151  56 151]]
[[504 123 103 276]]
[[471 144  75 200]]
[[274 135 103 277]]
[[ 83 140 115 307]]
[[632 141  58 159]]
[[477 116 114 305]]
[[631 149  60 162]]
[[458 121 118 325]]
[[650 151  50 136]]
[[571 128  97 260]]
[[385 116 123 330]]
[[582 150  61 165]]
[[370 116 122 327]]
[[616 151  50 141]]
[[415 121 122 327]]
[[259 123 116 311]]
[[655 165  48 136]]
[[566 141  82 220]]
[[425 140  94 253]]
[[508  78 138 371]]
[[570  98 126 338]]
[[607  94 118 353]]
[[601  88 121 356]]
[[516 120 122 327]]
[[551 150  68 213]]
[[427  90 133 355]]
[[194 137 116 310]]
[[ 38 126 128 318]]
[[660 168  66 176]]
[[455 141 114 305]]
[[575 163  53 143]]


[[310 107  56 233]]
[[218  25  64 263]]
[[716  78  59 184]]
[[710  87  28  82]]
[[147  21  75 270]]
[[677  92  32  86]]
[[396  60 109 314]]
[[543  76  56 234]]
[[282  35  75 259]]
[[375  78  60 246]]
[[365  92  74 253]]
[[258  28  96 364]]
[[435  75  79 360]]
[[247  33  91 342]]
[[395 110  53 215]]
[[208  55  84 266]]
[[157  37 105 335]]
[[610  40  83 285]]
[[519  70  85 275]]
[[447  80  87 296]]
[[432  62  66 247]]
[[583  75  82 292]]
[[245  83  78 257]]
[[375  46  83 300]]
[[695  54  75 271]]
[[305  82  64 203]]
[[266 112  97 314]]
[[325 128  57 189]]
[[ 29 133  44 160]]
[[ 94  72  33 103]]
[[ 56  50 135 396]]
[[362  67  86 239]]
[[476 108  39  99]]
[[546  60  47 145]]
[[488  43  55 153]]
[[571 117  36  91]]
[[653  52  42 143]]
[[242  60  74 257]]
[[105 102  51 146]]
[[171  20  64 253]]
[[208 108  81 295]]
[[289 108  56 223]]
[[443 120  92 326]]
[[221 140  60 189]]
[[371  53  89 346]]
[[328  43  93 350]]
[[377  96 103 309]]
[[393  78  98 350]]
[[342  59  78 313]]
[[487  48  95 385]]


[[204  99  78 258]]
[[250 113  67 292]]
[[310 109  58 183]]
[[321 110  53 178]]
[[311 105  60 190]]
[[282 117  50 216]]
[[540  96  79 234]]
[[557  88  78 236]]
[[582  72  75 263]]
[[538 114  65 205]]
[[478 103  67 229]]
[[478 137  53 173]]
[[303 107  45 174]]
[[311 153  60 190]]
[[313  57  82 312]]
[[407 119  68 225]]
[[366  48 107 328]]
[[261  31 117 384]]
[[242  33 100 309]]
[[315 160  67 258]]
[[438  48  88 344]]
[[300  61 126 385]]
[[350  48 134 357]]
[[215  50 108 376]]
[[156  33  67 218]]
[[247 101  83 268]]
[[145 125 109 317]]
[[503  45  60 198]]
[[537  43  71 214]]
[[444  76  49 146]]
[[510  49  65 212]]
[[551  56  71 225]]
[[439  78  47 150]]
[[443  78  45 148]]
[[581  35 112 368]]
[[586  38 110 368]]
[[161 110  92 287]]
[[431  74  46 149]]
[[450  70  53 171]]
[[286  32  76 296]]
[[222  30 129 414]]
[[531   1  64 207]]
[[572   1  72 218]]
[[460  47  46 153]]
[[541   8  74 216]]
[[578   1  76 240]]
[[460  45  50 157]]
[[460  45  42 155]]
[[206  40  86 306]]
[[371  39  77 289]]


[[571 108  61 178]]
[[235  59 103 370]]
[[288  98  91 276]]
[[391  81 107 349]]
[[356 113 118 313]]
[[311  98 123 322]]
[[343  56 108 320]]
[[460 111  58 175]]
[[400 117  42 113]]
[[459  63 137 367]]
[[404 233  51 138]]
[[408 235  50 134]]
[[340  35 161 393]]
[[634 245  56 151]]
[[520 233  51 157]]
[[541 188  63 215]]
[[303  82 132 357]]
[[292  60 127 383]]
[[175  81  67 273]]
[[180  82  70 225]]
[[303 101  81 289]]
[[352 103  67 230]]
[[411  27 128 414]]
[[521  36  97 374]]
[[259  89 128 344]]
[[353 104 104 323]]
[[ 78  88  72 246]]
[[114 124  86 270]]
[[  2  96  67 325]]
[[527   6 144 437]]
[[462  32 153 409]]
[[232  91  74 216]]
[[500  96  76 245]]
[[352  54  84 256]]
[[292 107  50 185]]
[[219  58 101 292]]
[[205  96  79 214]]
[[176  77  63 225]]
[[217  94  90 271]]
[[249  62  97 308]]
[[ 97   8 100 267]]
[[  4 111 117 334]]
[[608  80  91 280]]
[[428  58  61 221]]
[[ 23  98  76 285]]
[[  3  55  71 242]]
[[481  58  65 208]]
[[363  83 115 358]]
[[309  50 121 396]]
[[372  83 114 355]]


[[325 139 104 280]]
[[516 192 116 254]]
[[518 145  80 258]]
[[520 143  64 226]]
[[116 151  50 182]]
[[ 56 141  70 218]]
[[256  95  52 222]]
[[563 125  30 116]]
[[620  83  48 190]]
[[617  68  80 271]]
[[601 121  40 128]]
[[703  76  58 242]]
[[546  80  44 177]]
[[685  48  57 226]]
[[253 109  56 160]]
[[398 116  58 161]]
[[495 116  60 180]]
[[253 108  54 166]]
[[315 107  61 166]]
[[201 107  42 140]]
[[284 100  47 173]]
[[346 112  60 184]]
[[195 113  46 135]]
[[230 100  54 149]]
[[355 131  41 130]]
[[435 139  40 118]]
[[305  76  30  73]]
[[276  69  26  66]]
[[310  65  22  65]]
[[510  90  41 100]]
[[460  75  35 107]]
[[343  61  35  94]]
[[379  80  33 108]]
[[381  74  41 116]]
[[239  36  71 221]]
[[537 168  50 143]]
[[393 135  53 159]]
[[368 139  47 155]]
[[242 120  45 142]]
[[294 113  44 163]]
[[ 78  88  55 208]]
[[253  93 106 324]]
[[295  83  30  85]]
[[272  78  55 182]]
[[261  74  26 100]]
[[201  58  61 234]]
[[303 154  36 128]]
[[358 185  41 148]]
[[448 146  59 173]]
[[497 113  71 251]]


[[ 82 225  37 119]]
[[356  57 133 389]]
[[556 180  49 147]]
[[378  48 132 396]]
[[567  67 110 378]]
[[621 192  52 163]]
[[191  89  85 353]]
[[171  64  96 379]]
[[ 61 139  96 306]]
[[ 88 149  91 281]]
[[238  85 107 359]]
[[297  72 129 373]]
[[684 118  97 292]]
[[227 114  84 293]]
[[416 182  53 157]]
[[442 181  58 170]]
[[ 56 177  57 178]]
[[ 82 179  57 153]]
[[114 177  60 180]]
[[142 179  58 156]]
[[310 168  58 178]]
[[708 163  59 183]]
[[375 120  75 232]]
[[376 144  55 159]]
[[360 178  70 216]]
[[210 110  32  85]]
[[209 125  31  83]]
[[578 143  53 163]]
[[577 161  52 176]]
[[426 158  38 114]]
[[359 161  41 110]]
[[337 163  32 101]]
[[346 167  31  83]]
[[314 150  58 196]]
[[381 150  56 174]]
[[466 168  32 110]]
[[417 171  39 106]]
[[371 169  32 108]]
[[318 170  31  94]]
[[378 177  50 145]]
[[227 139  63 225]]
[[299 145  64 190]]
[[521  72 103 337]]
[[ 89 149  73 235]]
[[216 153  61 201]]
[[660  92  92 339]]
[[107   1 136 393]]
[[171  78  93 284]]
[[295  96  91 262]]
[[292  13 130 362]]


[[423 204  28  87]]
[[400 204  24  83]]
[[337 204  26  83]]
[[360 198  40 147]]
[[417 201  33 142]]
[[485 203  36 121]]
[[370 255  30 106]]
[[300 234  43 159]]
[[268 111  80 321]]
[[285 116  86 312]]
[[367 150  58 225]]
[[480 161  43 118]]
[[312 202  38  90]]
[[492 155  47 177]]
[[475 166  36 140]]
[[428 150  53 182]]
[[426 156  44 154]]
[[322 111  95 326]]
[[341 111  78 320]]
[[428 145  62 237]]
[[733 295  50 116]]
[[743 253  42  94]]
[[716 147  28  68]]
[[449 261  38 118]]
[[443 258  38 111]]
[[509 189  33 107]]
[[338 280  43 133]]
[[348 276  42 120]]
[[423 211  36 111]]
[[660 197  31  69]]
[[610 256  48 115]]
[[635 188  30  76]]
[[412 139  40 137]]
[[364 138  51 176]]
[[303 129  63 240]]
[[511 100  80 303]]
[[508 102  76 291]]
[[555 235  33  91]]
[[541 231  38  96]]
[[483 180  61 197]]
[[451 158  69 234]]
[[411 178  57 194]]
[[378 157  63 234]]
[[330 206  40 156]]
[[320 199  53 170]]
[[294 208  40 151]]
[[267 198  47 166]]
[[242 216  45 145]]
[[227 205  40 156]]
[[595 147  60 228]]


[[402 189  64 200]]
[[209  91  99 342]]
[[ 86  32 113 353]]
[[152 164  82 218]]
[[150 121  98 262]]
[[150 107 103 278]]
[[167 139  90 242]]
[[243 212  64 171]]
[[312 141  69 234]]
[[379 164  68 184]]
[[128 209  64 171]]
[[ 68 128  95 254]]
[[490 125  95 253]]
[[508 142  88 235]]
[[347 212  51 137]]
[[258 220  46 125]]
[[502 224  49 131]]
[[500 221  50 134]]
[[420 154  75 228]]
[[393 155  78 226]]
[[525 137  74 221]]
[[529 139  70 228]]
[[227 124  60 221]]
[[224 125  65 223]]
[[559 136  76 240]]
[[563 142  68 240]]
[[564 139  70 232]]
[[280 110  82 266]]
[[296 111  92 272]]
[[488  76  94 306]]
[[235  83  93 302]]
[[242  79 114 304]]
[[428  48 125 335]]
[[423 190  70 188]]
[[728 194  47 127]]
[[718 207  53 144]]
[[385 124  89 239]]
[[435  98  97 275]]
[[391 132  89 248]]
[[427 119  95 257]]
[[464 120  96 257]]
[[445 118  99 265]]
[[417  98 106 284]]
[[226 129  92 247]]
[[175 167  67 214]]
[[144 121  98 262]]
[[ 98 159  78 221]]
[[ 56 102  67 223]]
[[ 43 104  58 206]]
[[710 196  52 163]]


[[218 168  31  85]]
[[279 179  48 129]]
[[274 178  47 127]]
[[510  99 115 309]]
[[433 125  85 227]]
[[386 126  87 233]]
[[423  76 128 344]]
[[585 136  72 213]]
[[622 113  98 287]]
[[645 136  75 217]]
[[709 113  89 287]]
[[591 241  26  72]]
[[361 126  76 205]]
[[398 213  70 188]]
[[230 127  91 296]]
[[409 183  55 148]]
[[387 161  56 195]]
[[420 100 119 318]]
[[385 130  80 213]]
[[288 136 106 285]]
[[431 180  37 101]]
[[616 240  26  70]]
[[422 125  75 200]]
[[477 216  70 188]]
[[501 115  98 311]]
[[280 179  63 170]]
[[216 113  91 283]]
[[235 102  84 273]]
[[479 115 105 295]]
[[243 101  58 156]]
[[560 122  91 245]]
[[430 113  55 146]]
[[ 98 158  80 216]]
[[340 270  40 106]]
[[345 258  43 115]]
[[520 176  58 156]]
[[426 172  50 135]]
[[291  83 125 333]]
[[322 123  83 223]]
[[429 125 110 295]]
[[174  55  98 313]]
[[545 141  18  50]]
[[413 218  66 176]]
[[518 147  96 259]]
[[493  78 114 358]]
[[370 197  73 195]]
[[510 145  58 155]]
[[428 238  45 138]]
[[366 175  74 232]]
[[425 191  64 187]]


[[426 124  73 267]]
[[428 128  71 252]]
[[219 130  94 253]]
[[388 152  84 226]]
[[251  55 157 391]]
[[550  61 110 369]]
[[498  65  92 312]]
[[339  10 162 434]]
[[362  24 134 424]]
[[628  84  98 356]]
[[551  62  93 382]]
[[525  60 143 383]]
[[533   3 155 438]]
[[161  73  94 356]]
[[230 129  67 233]]
[[535  83  79 278]]
[[524  76  78 276]]
[[341  46 143 403]]
[[217  97  78 276]]
[[333  64 141 378]]
[[223  68  72 350]]
[[218  63  69 364]]
[[451 122  60 311]]
[[459 114  57 312]]
[[513 121  60 266]]
[[392 105  68 309]]
[[285 122  50 296]]
[[283 123  48 276]]
[[467 219  77 146]]
[[535 211  61 132]]
[[377 152 106 289]]
[[364 231  41 121]]
[[584 161  59 171]]
[[517  46 136 329]]
[[324  57 146 317]]
[[538 108 111 268]]
[[380 117 135 253]]
[[214 178  71 200]]
[[117 192  34 136]]
[[338 217  32 136]]
[[155 192  37 143]]
[[380 213  30 136]]
[[409 162  72 242]]
[[400 149 121 284]]
[[686 141  64 219]]
[[476 145 105 271]]
[[302 156  69 239]]
[[125 160  92 266]]
[[235 170  65 253]]
[[ 33 167  91 254]]


[[533  53 133 356]]
[[581 111  73 211]]
[[606 114  63 205]]
[[356 268  28  77]]
[[345 265  34  92]]
[[389 273  40 108]]
[[281 271  44 118]]
[[323 276  39 106]]
[[357 275  33  89]]
[[385 275  33  88]]
[[431 272  31  83]]
[[743 176  41 112]]
[[221 113  65 175]]
[[323 171  63 170]]
[[113 171  56 172]]
[[255 132  85 258]]
[[250 185  40 108]]
[[109 107  93 297]]
[[110 123  87 253]]
[[116 183  58 157]]
[[323 273  41 112]]
[[386 275  35  93]]
[[479 186  53 141]]
[[478 211  49 132]]
[[510 218  48 129]]
[[ 83 190  63 169]]
[[ 78 185  64 171]]
[[ 70 186  63 170]]
[[406 155  66 178]]
[[390 153  64 171]]
[[397 153  66 176]]
[[595 195  46 125]]
[[611 205  49 141]]
[[151 177  40 108]]
[[323 133  35  95]]
[[460 113  18  51]]
[[538 103  20  55]]
[[275 195  63 171]]
[[388 105  59 159]]
[[683 200  45 120]]
[[150 181  66 176]]
[[583  78  51 139]]
[[371 149  32  87]]
[[293 150  30  82]]
[[ 46 148  28  76]]
[[403 140  31  85]]
[[435 131  32  86]]
[[457 140  33  90]]
[[488 133  31  83]]
[[371 123 113 304]]


[[425 270  16  57]]
[[423 270  16  51]]
[[550 256  23  74]]
[[550 255  23  73]]
[[573 253  26  75]]
[[573 249  23  76]]
[[688 227  38 100]]
[[603 231  28  94]]
[[734 211  42 123]]
[[634 222  38 108]]
[[120 166  60 168]]
[[171  38  59 154]]
[[164 230  36 135]]
[[134 227  41 156]]
[[129 225  40 143]]
[[ 97 225  45 161]]
[[106 225  39 144]]
[[ 62 218  46 173]]
[[365 175  67 206]]
[[348 155  66 253]]
[[665 217  41 145]]
[[705 211  44 161]]
[[560 157  31 123]]
[[615 234  41 132]]
[[644 231  47 153]]
[[640 103  51 185]]
[[641  87  57 183]]
[[527 152  31 125]]
[[601 114  44 161]]
[[608 101  40 160]]
[[494 163  35 114]]
[[270  83  89 323]]
[[289  76  91 315]]
[[386 139  64 184]]
[[376  86  70 243]]
[[274 154  48 173]]
[[418 170  56 184]]
[[220 150  52 170]]
[[370 177  55 170]]
[[172 139  52 190]]
[[318 166  53 187]]
[[285 151  47 143]]
[[299 151  42 149]]
[[161 146  52 158]]
[[176 135  53 173]]
[[365 291  38 124]]
[[446 133  80 284]]
[[182 142  80 275]]
[[703 107  73 241]]
[[448 275  46 145]]


In [127]:
for i,v in enumerate(person['Person'][0]):
    for j, n in enumerate(v[2]):
        for nn in n:
            print(nn[0][0])
            print('-------')

s1.jpg
-------
s2.jpg
-------
s3.jpg
-------
s1.jpg
-------
s2.jpg
-------
s3.jpg
-------
s4.jpg
-------
s5.jpg
-------
s6.jpg
-------
s7.jpg
-------
s8.jpg
-------
s9.jpg
-------
s10.jpg
-------
s11.jpg
-------
s12.jpg
-------
s13.jpg
-------
s12.jpg
-------
s13.jpg
-------
s12.jpg
-------
s13.jpg
-------
s14.jpg
-------
s15.jpg
-------
s16.jpg
-------
s17.jpg
-------
s18.jpg
-------
s19.jpg
-------
s20.jpg
-------
s21.jpg
-------
s22.jpg
-------
s23.jpg
-------
s24.jpg
-------
s25.jpg
-------
s26.jpg
-------
s27.jpg
-------
s28.jpg
-------
s29.jpg
-------
s30.jpg
-------
s31.jpg
-------
s29.jpg
-------
s30.jpg
-------
s31.jpg
-------
s32.jpg
-------
s33.jpg
-------
s34.jpg
-------
s35.jpg
-------
s36.jpg
-------
s35.jpg
-------
s36.jpg
-------
s36.jpg
-------
s37.jpg
-------
s38.jpg
-------
s39.jpg
-------
s40.jpg
-------
s41.jpg
-------
s42.jpg
-------
s43.jpg
-------
s43.jpg
-------
s44.jpg
-------
s45.jpg
-------
s46.jpg
-------
s45.jpg
-------
s46.jpg
-------
s47.jpg
-------
s48.

s650.jpg
-------
s651.jpg
-------
s652.jpg
-------
s653.jpg
-------
s654.jpg
-------
s655.jpg
-------
s656.jpg
-------
s657.jpg
-------
s658.jpg
-------
s659.jpg
-------
s660.jpg
-------
s661.jpg
-------
s658.jpg
-------
s659.jpg
-------
s660.jpg
-------
s661.jpg
-------
s662.jpg
-------
s663.jpg
-------
s664.jpg
-------
s665.jpg
-------
s666.jpg
-------
s667.jpg
-------
s668.jpg
-------
s666.jpg
-------
s667.jpg
-------
s668.jpg
-------
s667.jpg
-------
s668.jpg
-------
s669.jpg
-------
s670.jpg
-------
s671.jpg
-------
s672.jpg
-------
s673.jpg
-------
s671.jpg
-------
s672.jpg
-------
s673.jpg
-------
s674.jpg
-------
s675.jpg
-------
s676.jpg
-------
s677.jpg
-------
s674.jpg
-------
s675.jpg
-------
s676.jpg
-------
s677.jpg
-------
s678.jpg
-------
s679.jpg
-------
s680.jpg
-------
s678.jpg
-------
s679.jpg
-------
s680.jpg
-------
s681.jpg
-------
s682.jpg
-------
s683.jpg
-------
s684.jpg
-------
s685.jpg
-------
s681.jpg
-------
s682.jpg
-------
s684.jpg
-------
s685.jpg
-----

s1313.jpg
-------
s1314.jpg
-------
s1312.jpg
-------
s1313.jpg
-------
s1315.jpg
-------
s1316.jpg
-------
s1317.jpg
-------
s1318.jpg
-------
s1317.jpg
-------
s1318.jpg
-------
s1319.jpg
-------
s1320.jpg
-------
s1319.jpg
-------
s1320.jpg
-------
s1321.jpg
-------
s1322.jpg
-------
s1323.jpg
-------
s1324.jpg
-------
s1325.jpg
-------
s1323.jpg
-------
s1324.jpg
-------
s1325.jpg
-------
s1323.jpg
-------
s1326.jpg
-------
s1327.jpg
-------
s1326.jpg
-------
s1328.jpg
-------
s1327.jpg
-------
s1326.jpg
-------
s1328.jpg
-------
s1329.jpg
-------
s1330.jpg
-------
s1331.jpg
-------
s1332.jpg
-------
s1328.jpg
-------
s1333.jpg
-------
s1334.jpg
-------
s1333.jpg
-------
s1334.jpg
-------
s1335.jpg
-------
s1336.jpg
-------
s1337.jpg
-------
s1338.jpg
-------
s1339.jpg
-------
s1340.jpg
-------
s1341.jpg
-------
s1342.jpg
-------
s1343.jpg
-------
s1344.jpg
-------
s1342.jpg
-------
s1343.jpg
-------
s1344.jpg
-------
s1345.jpg
-------
s1346.jpg
-------
s1347.jpg
-------
s1348.jpg


-------
s11621.jpg
-------
s11622.jpg
-------
s11621.jpg
-------
s11622.jpg
-------
s11623.jpg
-------
s11624.jpg
-------
s11625.jpg
-------
s11626.jpg
-------
s11627.jpg
-------
s11628.jpg
-------
s11628.jpg
-------
s11627.jpg
-------
s11629.jpg
-------
s11630.jpg
-------
s11629.jpg
-------
s11630.jpg
-------
s11631.jpg
-------
s11632.jpg
-------
s11633.jpg
-------
s11632.jpg
-------
s11631.jpg
-------
s11633.jpg
-------
s11634.jpg
-------
s11635.jpg
-------
s11636.jpg
-------
s11637.jpg
-------
s11638.jpg
-------
s11637.jpg
-------
s11638.jpg
-------
s11639.jpg
-------
s11640.jpg
-------
s11637.jpg
-------
s11638.jpg
-------
s11639.jpg
-------
s11640.jpg
-------
s11640.jpg
-------
s11639.jpg
-------
s11641.jpg
-------
s11642.jpg
-------
s11643.jpg
-------
s11643.jpg
-------
s11644.jpg
-------
s11645.jpg
-------
s11646.jpg
-------
s11647.jpg
-------
s11648.jpg
-------
s11649.jpg
-------
s11650.jpg
-------
s11651.jpg
-------
s11652.jpg
-------
s11653.jpg
-------
s11654.jpg
-------
s116

-------
s12203.jpg
-------
s12204.jpg
-------
s12205.jpg
-------
s12206.jpg
-------
s12207.jpg
-------
s12208.jpg
-------
s12206.jpg
-------
s12207.jpg
-------
s12208.jpg
-------
s12206.jpg
-------
s12207.jpg
-------
s12208.jpg
-------
s12206.jpg
-------
s12207.jpg
-------
s12208.jpg
-------
s12209.jpg
-------
s12210.jpg
-------
s12212.jpg
-------
s12213.jpg
-------
s12214.jpg
-------
s12213.jpg
-------
s12214.jpg
-------
s12215.jpg
-------
s12215.jpg
-------
s12216.jpg
-------
s12215.jpg
-------
s12216.jpg
-------
s12217.jpg
-------
s12215.jpg
-------
s12216.jpg
-------
s12217.jpg
-------
s12218.jpg
-------
s12219.jpg
-------
s12220.jpg
-------
s12221.jpg
-------
s12222.jpg
-------
s12223.jpg
-------
s12222.jpg
-------
s12224.jpg
-------
s12225.jpg
-------
s12226.jpg
-------
s12227.jpg
-------
s12228.jpg
-------
s12229.jpg
-------
s12230.jpg
-------
s12231.jpg
-------
s12222.jpg
-------
s12224.jpg
-------
s12232.jpg
-------
s12224.jpg
-------
s12225.jpg
-------
s12226.jpg
-------
s122

s1789.jpg
-------
s1790.jpg
-------
s1791.jpg
-------
s1792.jpg
-------
s1793.jpg
-------
s1794.jpg
-------
s1791.jpg
-------
s1794.jpg
-------
s1793.jpg
-------
s1794.jpg
-------
s1795.jpg
-------
s1796.jpg
-------
s1797.jpg
-------
s1798.jpg
-------
s1799.jpg
-------
s1800.jpg
-------
s1801.jpg
-------
s1802.jpg
-------
s1803.jpg
-------
s1804.jpg
-------
s1805.jpg
-------
s1806.jpg
-------
s1803.jpg
-------
s1804.jpg
-------
s1805.jpg
-------
s1806.jpg
-------
s1807.jpg
-------
s1808.jpg
-------
s1809.jpg
-------
s1810.jpg
-------
s1811.jpg
-------
s1807.jpg
-------
s1810.jpg
-------
s1812.jpg
-------
s1813.jpg
-------
s1814.jpg
-------
s1815.jpg
-------
s1816.jpg
-------
s1814.jpg
-------
s1817.jpg
-------
s1817.jpg
-------
s1818.jpg
-------
s1819.jpg
-------
s1817.jpg
-------
s1819.jpg
-------
s1820.jpg
-------
s1821.jpg
-------
s1822.jpg
-------
s1821.jpg
-------
s1822.jpg
-------
s1821.jpg
-------
s1822.jpg
-------
s1823.jpg
-------
s1824.jpg
-------
s1825.jpg
-------
s1826.jpg


s2379.jpg
-------
s2380.jpg
-------
s2381.jpg
-------
s2382.jpg
-------
s2381.jpg
-------
s2382.jpg
-------
s2383.jpg
-------
s2384.jpg
-------
s2385.jpg
-------
s2385.jpg
-------
s2386.jpg
-------
s2387.jpg
-------
s2388.jpg
-------
s2389.jpg
-------
s2390.jpg
-------
s2391.jpg
-------
s2392.jpg
-------
s2389.jpg
-------
s2390.jpg
-------
s2393.jpg
-------
s2394.jpg
-------
s2393.jpg
-------
s2394.jpg
-------
s2395.jpg
-------
s2395.jpg
-------
s2396.jpg
-------
s2397.jpg
-------
s2398.jpg
-------
s2399.jpg
-------
s2400.jpg
-------
s2398.jpg
-------
s2401.jpg
-------
s2402.jpg
-------
s2403.jpg
-------
s2401.jpg
-------
s2402.jpg
-------
s2404.jpg
-------
s2405.jpg
-------
s2406.jpg
-------
s2404.jpg
-------
s2405.jpg
-------
s2407.jpg
-------
s2406.jpg
-------
s2408.jpg
-------
s2409.jpg
-------
s2410.jpg
-------
s2411.jpg
-------
s2408.jpg
-------
s2409.jpg
-------
s2410.jpg
-------
s2411.jpg
-------
s2409.jpg
-------
s2410.jpg
-------
s2412.jpg
-------
s2413.jpg
-------
s2412.jpg


-------
s2912.jpg
-------
s2913.jpg
-------
s2911.jpg
-------
s2912.jpg
-------
s2913.jpg
-------
s2914.jpg
-------
s2915.jpg
-------
s2916.jpg
-------
s2917.jpg
-------
s2918.jpg
-------
s2919.jpg
-------
s2920.jpg
-------
s2921.jpg
-------
s2922.jpg
-------
s2923.jpg
-------
s2924.jpg
-------
s2925.jpg
-------
s2921.jpg
-------
s2926.jpg
-------
s2924.jpg
-------
s2925.jpg
-------
s2927.jpg
-------
s2928.jpg
-------
s2927.jpg
-------
s2928.jpg
-------
s2929.jpg
-------
s2930.jpg
-------
s2931.jpg
-------
s2932.jpg
-------
s2926.jpg
-------
s2933.jpg
-------
s2933.jpg
-------
s2934.jpg
-------
s2935.jpg
-------
s2936.jpg
-------
s2934.jpg
-------
s2936.jpg
-------
s2937.jpg
-------
s2938.jpg
-------
s2939.jpg
-------
s2940.jpg
-------
s2941.jpg
-------
s2942.jpg
-------
s2943.jpg
-------
s2944.jpg
-------
s2940.jpg
-------
s2941.jpg
-------
s2941.jpg
-------
s2943.jpg
-------
s2943.jpg
-------
s2944.jpg
-------
s2945.jpg
-------
s2946.jpg
-------
s2947.jpg
-------
s2948.jpg
-------
s2

-------
s3592.jpg
-------
s3593.jpg
-------
s3593.jpg
-------
s3594.jpg
-------
s3593.jpg
-------
s3594.jpg
-------
s3595.jpg
-------
s3596.jpg
-------
s3597.jpg
-------
s3598.jpg
-------
s3599.jpg
-------
s3600.jpg
-------
s3600.jpg
-------
s3599.jpg
-------
s3601.jpg
-------
s3602.jpg
-------
s3601.jpg
-------
s3602.jpg
-------
s3603.jpg
-------
s3604.jpg
-------
s3603.jpg
-------
s3604.jpg
-------
s3605.jpg
-------
s3606.jpg
-------
s3605.jpg
-------
s3606.jpg
-------
s3607.jpg
-------
s3608.jpg
-------
s3607.jpg
-------
s3608.jpg
-------
s3607.jpg
-------
s3608.jpg
-------
s3608.jpg
-------
s3607.jpg
-------
s3607.jpg
-------
s3608.jpg
-------
s3609.jpg
-------
s3610.jpg
-------
s3610.jpg
-------
s3609.jpg
-------
s3610.jpg
-------
s3609.jpg
-------
s3611.jpg
-------
s3612.jpg
-------
s3611.jpg
-------
s3612.jpg
-------
s3613.jpg
-------
s3614.jpg
-------
s3615.jpg
-------
s3613.jpg
-------
s3614.jpg
-------
s3615.jpg
-------
s3617.jpg
-------
s3616.jpg
-------
s3616.jpg
-------
s3

s4068.jpg
-------
s4069.jpg
-------
s4070.jpg
-------
s4070.jpg
-------
s4071.jpg
-------
s4072.jpg
-------
s4073.jpg
-------
s4074.jpg
-------
s4075.jpg
-------
s4076.jpg
-------
s4077.jpg
-------
s4078.jpg
-------
s4079.jpg
-------
s4078.jpg
-------
s4079.jpg
-------
s4078.jpg
-------
s4079.jpg
-------
s4080.jpg
-------
s4081.jpg
-------
s4082.jpg
-------
s4083.jpg
-------
s4083.jpg
-------
s4082.jpg
-------
s4084.jpg
-------
s4085.jpg
-------
s4086.jpg
-------
s4087.jpg
-------
s4085.jpg
-------
s4088.jpg
-------
s4089.jpg
-------
s4090.jpg
-------
s4089.jpg
-------
s4089.jpg
-------
s4090.jpg
-------
s4091.jpg
-------
s4092.jpg
-------
s4093.jpg
-------
s4094.jpg
-------
s4093.jpg
-------
s4091.jpg
-------
s4092.jpg
-------
s4094.jpg
-------
s4095.jpg
-------
s4088.jpg
-------
s4095.jpg
-------
s4096.jpg
-------
s4095.jpg
-------
s4096.jpg
-------
s4096.jpg
-------
s4097.jpg
-------
s4096.jpg
-------
s4097.jpg
-------
s4098.jpg
-------
s4045.jpg
-------
s4099.jpg
-------
s4100.jpg


s4590.jpg
-------
s4591.jpg
-------
s4592.jpg
-------
s4593.jpg
-------
s4592.jpg
-------
s4593.jpg
-------
s4592.jpg
-------
s4593.jpg
-------
s4010.jpg
-------
s4594.jpg
-------
s4010.jpg
-------
s4594.jpg
-------
s3746.jpg
-------
s4595.jpg
-------
s4596.jpg
-------
s4597.jpg
-------
s4598.jpg
-------
s4599.jpg
-------
s4600.jpg
-------
s4600.jpg
-------
s4601.jpg
-------
s3756.jpg
-------
s3757.jpg
-------
s4602.jpg
-------
s4603.jpg
-------
s4602.jpg
-------
s4603.jpg
-------
s4604.jpg
-------
s4605.jpg
-------
s4606.jpg
-------
s4607.jpg
-------
s4608.jpg
-------
s4609.jpg
-------
s4610.jpg
-------
s3805.jpg
-------
s4610.jpg
-------
s3805.jpg
-------
s4611.jpg
-------
s3806.jpg
-------
s4612.jpg
-------
s4613.jpg
-------
s4612.jpg
-------
s4613.jpg
-------
s4614.jpg
-------
s4615.jpg
-------
s3877.jpg
-------
s3874.jpg
-------
s3880.jpg
-------
s3882.jpg
-------
s3880.jpg
-------
s3882.jpg
-------
s3903.jpg
-------
s3904.jpg
-------
s3905.jpg
-------
s3946.jpg
-------
s4616.jpg


s5132.jpg
-------
s5133.jpg
-------
s5132.jpg
-------
s5133.jpg
-------
s5132.jpg
-------
s5131.jpg
-------
s5137.jpg
-------
s5138.jpg
-------
s5139.jpg
-------
s5140.jpg
-------
s5141.jpg
-------
s5139.jpg
-------
s5140.jpg
-------
s5141.jpg
-------
s5142.jpg
-------
s5139.jpg
-------
s5140.jpg
-------
s5142.jpg
-------
s5135.jpg
-------
s5136.jpg
-------
s5143.jpg
-------
s5144.jpg
-------
s5143.jpg
-------
s5144.jpg
-------
s5145.jpg
-------
s5146.jpg
-------
s5144.jpg
-------
s5145.jpg
-------
s5145.jpg
-------
s5146.jpg
-------
s5147.jpg
-------
s5148.jpg
-------
s5149.jpg
-------
s5150.jpg
-------
s5151.jpg
-------
s5152.jpg
-------
s5153.jpg
-------
s5151.jpg
-------
s5153.jpg
-------
s5154.jpg
-------
s5155.jpg
-------
s5156.jpg
-------
s5157.jpg
-------
s5158.jpg
-------
s5159.jpg
-------
s5158.jpg
-------
s5160.jpg
-------
s5161.jpg
-------
s5162.jpg
-------
s5163.jpg
-------
s5164.jpg
-------
s5163.jpg
-------
s5164.jpg
-------
s5165.jpg
-------
s5166.jpg
-------
s5167.jpg


-------
s5794.jpg
-------
s5795.jpg
-------
s5794.jpg
-------
s5795.jpg
-------
s5796.jpg
-------
s5797.jpg
-------
s5796.jpg
-------
s5797.jpg
-------
s5797.jpg
-------
s5798.jpg
-------
s5799.jpg
-------
s5797.jpg
-------
s5798.jpg
-------
s5798.jpg
-------
s5799.jpg
-------
s5800.jpg
-------
s5801.jpg
-------
s5800.jpg
-------
s5801.jpg
-------
s5800.jpg
-------
s5801.jpg
-------
s5800.jpg
-------
s5801.jpg
-------
s5800.jpg
-------
s5801.jpg
-------
s5802.jpg
-------
s5803.jpg
-------
s5804.jpg
-------
s5802.jpg
-------
s5803.jpg
-------
s5804.jpg
-------
s5803.jpg
-------
s5805.jpg
-------
s5806.jpg
-------
s5807.jpg
-------
s5808.jpg
-------
s5809.jpg
-------
s5808.jpg
-------
s5809.jpg
-------
s5806.jpg
-------
s5810.jpg
-------
s5811.jpg
-------
s5812.jpg
-------
s5810.jpg
-------
s5811.jpg
-------
s5812.jpg
-------
s5812.jpg
-------
s5813.jpg
-------
s5814.jpg
-------
s5815.jpg
-------
s5805.jpg
-------
s5816.jpg
-------
s5817.jpg
-------
s5818.jpg
-------
s5815.jpg
-------
s5

s6304.jpg
-------
s6303.jpg
-------
s6305.jpg
-------
s6306.jpg
-------
s6307.jpg
-------
s6308.jpg
-------
s6309.jpg
-------
s6310.jpg
-------
s6311.jpg
-------
s6310.jpg
-------
s6311.jpg
-------
s6310.jpg
-------
s6311.jpg
-------
s6312.jpg
-------
s6313.jpg
-------
s6314.jpg
-------
s6315.jpg
-------
s6316.jpg
-------
s6314.jpg
-------
s6315.jpg
-------
s6316.jpg
-------
s6317.jpg
-------
s6318.jpg
-------
s6317.jpg
-------
s6318.jpg
-------
s6319.jpg
-------
s6320.jpg
-------
s6321.jpg
-------
s6322.jpg
-------
s6323.jpg
-------
s6322.jpg
-------
s6323.jpg
-------
s6324.jpg
-------
s6325.jpg
-------
s6324.jpg
-------
s6325.jpg
-------
s6326.jpg
-------
s6327.jpg
-------
s6328.jpg
-------
s6329.jpg
-------
s6250.jpg
-------
s6251.jpg
-------
s6330.jpg
-------
s6331.jpg
-------
s6332.jpg
-------
s6333.jpg
-------
s6354.jpg
-------
s6355.jpg
-------
s6356.jpg
-------
s6357.jpg
-------
s6358.jpg
-------
s6359.jpg
-------
s6360.jpg
-------
s6361.jpg
-------
s6362.jpg
-------
s6360.jpg


s6821.jpg
-------
s6818.jpg
-------
s6820.jpg
-------
s6821.jpg
-------
s6818.jpg
-------
s6820.jpg
-------
s6821.jpg
-------
s6822.jpg
-------
s6823.jpg
-------
s6822.jpg
-------
s6823.jpg
-------
s6822.jpg
-------
s6823.jpg
-------
s6822.jpg
-------
s6823.jpg
-------
s6824.jpg
-------
s6825.jpg
-------
s6826.jpg
-------
s6827.jpg
-------
s6828.jpg
-------
s6825.jpg
-------
s6826.jpg
-------
s6828.jpg
-------
s6827.jpg
-------
s6826.jpg
-------
s6828.jpg
-------
s6827.jpg
-------
s6829.jpg
-------
s6830.jpg
-------
s6831.jpg
-------
s6827.jpg
-------
s6829.jpg
-------
s6830.jpg
-------
s6831.jpg
-------
s6832.jpg
-------
s6830.jpg
-------
s6831.jpg
-------
s6833.jpg
-------
s6834.jpg
-------
s6835.jpg
-------
s6836.jpg
-------
s6832.jpg
-------
s6833.jpg
-------
s6837.jpg
-------
s6838.jpg
-------
s6837.jpg
-------
s6834.jpg
-------
s6835.jpg
-------
s6834.jpg
-------
s6835.jpg
-------
s6839.jpg
-------
s6840.jpg
-------
s6836.jpg
-------
s6833.jpg
-------
s6839.jpg
-------
s6840.jpg


-------
s7397.jpg
-------
s7395.jpg
-------
s7396.jpg
-------
s7397.jpg
-------
s7398.jpg
-------
s7399.jpg
-------
s7398.jpg
-------
s7399.jpg
-------
s7400.jpg
-------
s7401.jpg
-------
s7400.jpg
-------
s7401.jpg
-------
s7402.jpg
-------
s7403.jpg
-------
s7402.jpg
-------
s7403.jpg
-------
s7402.jpg
-------
s7403.jpg
-------
s7402.jpg
-------
s7403.jpg
-------
s7402.jpg
-------
s7403.jpg
-------
s7402.jpg
-------
s7403.jpg
-------
s7404.jpg
-------
s7405.jpg
-------
s7406.jpg
-------
s7407.jpg
-------
s7408.jpg
-------
s7407.jpg
-------
s7408.jpg
-------
s7409.jpg
-------
s7410.jpg
-------
s7411.jpg
-------
s7412.jpg
-------
s7413.jpg
-------
s7414.jpg
-------
s7414.jpg
-------
s7411.jpg
-------
s7414.jpg
-------
s7411.jpg
-------
s7411.jpg
-------
s7412.jpg
-------
s7415.jpg
-------
s7416.jpg
-------
s7417.jpg
-------
s7418.jpg
-------
s7419.jpg
-------
s7418.jpg
-------
s7419.jpg
-------
s7418.jpg
-------
s7419.jpg
-------
s7418.jpg
-------
s7419.jpg
-------
s7420.jpg
-------
s7

-------
s7979.jpg
-------
s7981.jpg
-------
s7982.jpg
-------
s7983.jpg
-------
s7984.jpg
-------
s7981.jpg
-------
s7982.jpg
-------
s7983.jpg
-------
s7985.jpg
-------
s7986.jpg
-------
s7987.jpg
-------
s7988.jpg
-------
s7987.jpg
-------
s7988.jpg
-------
s7989.jpg
-------
s7990.jpg
-------
s7991.jpg
-------
s7992.jpg
-------
s7993.jpg
-------
s7994.jpg
-------
s7995.jpg
-------
s7996.jpg
-------
s7994.jpg
-------
s7995.jpg
-------
s7996.jpg
-------
s7997.jpg
-------
s7998.jpg
-------
s7999.jpg
-------
s8000.jpg
-------
s8001.jpg
-------
s8002.jpg
-------
s8000.jpg
-------
s8001.jpg
-------
s8002.jpg
-------
s8003.jpg
-------
s8004.jpg
-------
s8005.jpg
-------
s8006.jpg
-------
s8007.jpg
-------
s8008.jpg
-------
s8009.jpg
-------
s8010.jpg
-------
s8011.jpg
-------
s8012.jpg
-------
s8013.jpg
-------
s8014.jpg
-------
s8015.jpg
-------
s8016.jpg
-------
s8017.jpg
-------
s8018.jpg
-------
s8019.jpg
-------
s8020.jpg
-------
s8021.jpg
-------
s8022.jpg
-------
s8023.jpg
-------
s8

s8684.jpg
-------
s8685.jpg
-------
s8686.jpg
-------
s8687.jpg
-------
s8688.jpg
-------
s8689.jpg
-------
s8690.jpg
-------
s8691.jpg
-------
s8692.jpg
-------
s8693.jpg
-------
s8694.jpg
-------
s8695.jpg
-------
s8696.jpg
-------
s8697.jpg
-------
s8698.jpg
-------
s8699.jpg
-------
s8700.jpg
-------
s8701.jpg
-------
s8702.jpg
-------
s8703.jpg
-------
s8704.jpg
-------
s8705.jpg
-------
s8704.jpg
-------
s8705.jpg
-------
s8706.jpg
-------
s8707.jpg
-------
s8706.jpg
-------
s8707.jpg
-------
s8708.jpg
-------
s8709.jpg
-------
s8710.jpg
-------
s8711.jpg
-------
s8712.jpg
-------
s8713.jpg
-------
s8714.jpg
-------
s8715.jpg
-------
s8716.jpg
-------
s8717.jpg
-------
s8718.jpg
-------
s8719.jpg
-------
s8720.jpg
-------
s8721.jpg
-------
s8722.jpg
-------
s8723.jpg
-------
s8724.jpg
-------
s8725.jpg
-------
s8726.jpg
-------
s8727.jpg
-------
s8728.jpg
-------
s8729.jpg
-------
s8730.jpg
-------
s8731.jpg
-------
s8732.jpg
-------
s8733.jpg
-------
s8734.jpg
-------
s8735.jpg


s9243.jpg
-------
s9244.jpg
-------
s9245.jpg
-------
s9246.jpg
-------
s9247.jpg
-------
s9248.jpg
-------
s9247.jpg
-------
s9248.jpg
-------
s9249.jpg
-------
s9250.jpg
-------
s9249.jpg
-------
s9250.jpg
-------
s9251.jpg
-------
s9252.jpg
-------
s9251.jpg
-------
s9252.jpg
-------
s9253.jpg
-------
s9254.jpg
-------
s9253.jpg
-------
s9254.jpg
-------
s9253.jpg
-------
s9254.jpg
-------
s9255.jpg
-------
s9256.jpg
-------
s9257.jpg
-------
s9257.jpg
-------
s9258.jpg
-------
s9259.jpg
-------
s9260.jpg
-------
s9259.jpg
-------
s9260.jpg
-------
s9259.jpg
-------
s9260.jpg
-------
s9261.jpg
-------
s9262.jpg
-------
s9261.jpg
-------
s9262.jpg
-------
s9261.jpg
-------
s9262.jpg
-------
s9263.jpg
-------
s9264.jpg
-------
s9265.jpg
-------
s9266.jpg
-------
s9267.jpg
-------
s9268.jpg
-------
s9269.jpg
-------
s9265.jpg
-------
s9267.jpg
-------
s9268.jpg
-------
s9265.jpg
-------
s9266.jpg
-------
s9267.jpg
-------
s9268.jpg
-------
s9270.jpg
-------
s9267.jpg
-------
s9268.jpg


-------
s9712.jpg
-------
s9713.jpg
-------
s9708.jpg
-------
s9709.jpg
-------
s9710.jpg
-------
s9711.jpg
-------
s9712.jpg
-------
s9713.jpg
-------
s9714.jpg
-------
s9715.jpg
-------
s9716.jpg
-------
s9714.jpg
-------
s9715.jpg
-------
s9716.jpg
-------
s9717.jpg
-------
s9718.jpg
-------
s9717.jpg
-------
s9718.jpg
-------
s9719.jpg
-------
s9720.jpg
-------
s9719.jpg
-------
s9720.jpg
-------
s9719.jpg
-------
s9720.jpg
-------
s9721.jpg
-------
s9722.jpg
-------
s9723.jpg
-------
s9724.jpg
-------
s9725.jpg
-------
s9726.jpg
-------
s9725.jpg
-------
s9726.jpg
-------
s9727.jpg
-------
s9728.jpg
-------
s9729.jpg
-------
s9730.jpg
-------
s9727.jpg
-------
s9728.jpg
-------
s9730.jpg
-------
s9727.jpg
-------
s9729.jpg
-------
s9731.jpg
-------
s9732.jpg
-------
s9733.jpg
-------
s9731.jpg
-------
s9732.jpg
-------
s9733.jpg
-------
s9734.jpg
-------
s9735.jpg
-------
s9734.jpg
-------
s9735.jpg
-------
s9736.jpg
-------
s9737.jpg
-------
s9738.jpg
-------
s9739.jpg
-------
s9

s10264.jpg
-------
s10265.jpg
-------
s10266.jpg
-------
s10267.jpg
-------
s10264.jpg
-------
s10265.jpg
-------
s10269.jpg
-------
s10270.jpg
-------
s10271.jpg
-------
s10272.jpg
-------
s10273.jpg
-------
s10274.jpg
-------
s10275.jpg
-------
s10276.jpg
-------
s10277.jpg
-------
s10278.jpg
-------
s10279.jpg
-------
s10280.jpg
-------
s10281.jpg
-------
s10282.jpg
-------
s10283.jpg
-------
s10284.jpg
-------
s10279.jpg
-------
s10280.jpg
-------
s10281.jpg
-------
s10282.jpg
-------
s10283.jpg
-------
s10284.jpg
-------
s10285.jpg
-------
s10286.jpg
-------
s10287.jpg
-------
s10288.jpg
-------
s10289.jpg
-------
s10290.jpg
-------
s10291.jpg
-------
s10292.jpg
-------
s10293.jpg
-------
s10291.jpg
-------
s10292.jpg
-------
s10291.jpg
-------
s10292.jpg
-------
s10294.jpg
-------
s10293.jpg
-------
s10295.jpg
-------
s10296.jpg
-------
s10297.jpg
-------
s10298.jpg
-------
s10297.jpg
-------
s10298.jpg
-------
s10299.jpg
-------
s10300.jpg
-------
s10297.jpg
-------
s10298.jpg
-

s10718.jpg
-------
s10719.jpg
-------
s10720.jpg
-------
s10721.jpg
-------
s10722.jpg
-------
s10723.jpg
-------
s10724.jpg
-------
s10725.jpg
-------
s10726.jpg
-------
s10727.jpg
-------
s10726.jpg
-------
s10727.jpg
-------
s10728.jpg
-------
s10729.jpg
-------
s10730.jpg
-------
s10731.jpg
-------
s10732.jpg
-------
s10733.jpg
-------
s10732.jpg
-------
s10733.jpg
-------
s10734.jpg
-------
s10735.jpg
-------
s10736.jpg
-------
s10737.jpg
-------
s10736.jpg
-------
s10737.jpg
-------
s10738.jpg
-------
s10739.jpg
-------
s10740.jpg
-------
s10741.jpg
-------
s10742.jpg
-------
s10743.jpg
-------
s10742.jpg
-------
s10743.jpg
-------
s10743.jpg
-------
s10744.jpg
-------
s10743.jpg
-------
s10744.jpg
-------
s10745.jpg
-------
s10746.jpg
-------
s10747.jpg
-------
s10748.jpg
-------
s10747.jpg
-------
s10748.jpg
-------
s10749.jpg
-------
s10750.jpg
-------
s10749.jpg
-------
s10751.jpg
-------
s10752.jpg
-------
s10753.jpg
-------
s10751.jpg
-------
s10754.jpg
-------
s10755.jpg
-

s17133.jpg
-------
s17134.jpg
-------
s17135.jpg
-------
s17133.jpg
-------
s17134.jpg
-------
s17136.jpg
-------
s17137.jpg
-------
s17138.jpg
-------
s17139.jpg
-------
s17140.jpg
-------
s17141.jpg
-------
s17139.jpg
-------
s17140.jpg
-------
s17141.jpg
-------
s17139.jpg
-------
s17140.jpg
-------
s17141.jpg
-------
s17142.jpg
-------
s17143.jpg
-------
s17144.jpg
-------
s17145.jpg
-------
s17146.jpg
-------
s17147.jpg
-------
s17148.jpg
-------
s17140.jpg
-------
s17141.jpg
-------
s17142.jpg
-------
s17143.jpg
-------
s17144.jpg
-------
s17146.jpg
-------
s17147.jpg
-------
s17149.jpg
-------
s17150.jpg
-------
s17151.jpg
-------
s17148.jpg
-------
s17152.jpg
-------
s17153.jpg
-------
s17154.jpg
-------
s17146.jpg
-------
s17147.jpg
-------
s17149.jpg
-------
s17150.jpg
-------
s17151.jpg
-------
s17148.jpg
-------
s17149.jpg
-------
s17150.jpg
-------
s17151.jpg
-------
s17148.jpg
-------
s17149.jpg
-------
s17150.jpg
-------
s17151.jpg
-------
s17148.jpg
-------
s17155.jpg
-

s17609.jpg
-------
s17610.jpg
-------
s17611.jpg
-------
s17609.jpg
-------
s17610.jpg
-------
s17611.jpg
-------
s17612.jpg
-------
s17613.jpg
-------
s17614.jpg
-------
s17615.jpg
-------
s17612.jpg
-------
s17613.jpg
-------
s17614.jpg
-------
s17615.jpg
-------
s17616.jpg
-------
s17617.jpg
-------
s17618.jpg
-------
s17619.jpg
-------
s17615.jpg
-------
s17616.jpg
-------
s17617.jpg
-------
s17618.jpg
-------
s17619.jpg
-------
s17615.jpg
-------
s17620.jpg
-------
s17621.jpg
-------
s17622.jpg
-------
s17623.jpg
-------
s17624.jpg
-------
s17625.jpg
-------
s17626.jpg
-------
s17627.jpg
-------
s17628.jpg
-------
s17620.jpg
-------
s17621.jpg
-------
s17620.jpg
-------
s17621.jpg
-------
s17629.jpg
-------
s17625.jpg
-------
s17626.jpg
-------
s17628.jpg
-------
s17620.jpg
-------
s17621.jpg
-------
s17625.jpg
-------
s17626.jpg
-------
s17628.jpg
-------
s17620.jpg
-------
s17621.jpg
-------
s17625.jpg
-------
s17626.jpg
-------
s17628.jpg
-------
s17620.jpg
-------
s17621.jpg
-

-------
s17913.jpg
-------
s17914.jpg
-------
s17916.jpg
-------
s17910.jpg
-------
s17915.jpg
-------
s17911.jpg
-------
s17913.jpg
-------
s17917.jpg
-------
s17918.jpg
-------
s17917.jpg
-------
s17918.jpg
-------
s17919.jpg
-------
s17917.jpg
-------
s17920.jpg
-------
s17918.jpg
-------
s17919.jpg
-------
s17920.jpg
-------
s17919.jpg
-------
s17919.jpg
-------
s17921.jpg
-------
s17922.jpg
-------
s17921.jpg
-------
s17922.jpg
-------
s17923.jpg
-------
s17924.jpg
-------
s17925.jpg
-------
s17926.jpg
-------
s17923.jpg
-------
s17924.jpg
-------
s17925.jpg
-------
s17927.jpg
-------
s17928.jpg
-------
s17929.jpg
-------
s17930.jpg
-------
s17926.jpg
-------
s17923.jpg
-------
s17924.jpg
-------
s17931.jpg
-------
s17932.jpg
-------
s17933.jpg
-------
s17926.jpg
-------
s17923.jpg
-------
s17924.jpg
-------
s17925.jpg
-------
s17923.jpg
-------
s17924.jpg
-------
s17926.jpg
-------
s17923.jpg
-------
s17924.jpg
-------
s17925.jpg
-------
s17934.jpg
-------
s17935.jpg
-------
s179

s15889.jpg
-------
s15887.jpg
-------
s15888.jpg
-------
s15889.jpg
-------
s15887.jpg
-------
s15888.jpg
-------
s15886.jpg
-------
s15887.jpg
-------
s15888.jpg
-------
s15888.jpg
-------
s15886.jpg
-------
s15889.jpg
-------
s15888.jpg
-------
s15886.jpg
-------
s15888.jpg
-------
s15889.jpg
-------
s15890.jpg
-------
s15891.jpg
-------
s15892.jpg
-------
s15893.jpg
-------
s15894.jpg
-------
s15895.jpg
-------
s15896.jpg
-------
s15897.jpg
-------
s15898.jpg
-------
s15899.jpg
-------
s15900.jpg
-------
s15901.jpg
-------
s15900.jpg
-------
s15901.jpg
-------
s15902.jpg
-------
s15900.jpg
-------
s15901.jpg
-------
s15902.jpg
-------
s15903.jpg
-------
s15904.jpg
-------
s15903.jpg
-------
s15904.jpg
-------
s15903.jpg
-------
s15904.jpg
-------
s15903.jpg
-------
s15904.jpg
-------
s15903.jpg
-------
s15904.jpg
-------
s15903.jpg
-------
s15904.jpg
-------
s15905.jpg
-------
s15906.jpg
-------
s15907.jpg
-------
s15905.jpg
-------
s15906.jpg
-------
s15907.jpg
-------
s15908.jpg
-

-------
s16339.jpg
-------
s16325.jpg
-------
s16340.jpg
-------
s16341.jpg
-------
s16342.jpg
-------
s16322.jpg
-------
s16343.jpg
-------
s16344.jpg
-------
s16345.jpg
-------
s16346.jpg
-------
s16347.jpg
-------
s16346.jpg
-------
s16347.jpg
-------
s16346.jpg
-------
s16347.jpg
-------
s16348.jpg
-------
s16349.jpg
-------
s16350.jpg
-------
s16351.jpg
-------
s16352.jpg
-------
s16353.jpg
-------
s16354.jpg
-------
s16355.jpg
-------
s16356.jpg
-------
s16357.jpg
-------
s16358.jpg
-------
s16359.jpg
-------
s16360.jpg
-------
s16361.jpg
-------
s16362.jpg
-------
s16363.jpg
-------
s16364.jpg
-------
s16365.jpg
-------
s16366.jpg
-------
s16367.jpg
-------
s16368.jpg
-------
s16369.jpg
-------
s16370.jpg
-------
s16371.jpg
-------
s16372.jpg
-------
s16373.jpg
-------
s16374.jpg
-------
s16375.jpg
-------
s16376.jpg
-------
s16377.jpg
-------
s16378.jpg
-------
s16379.jpg
-------
s16380.jpg
-------
s16381.jpg
-------
s16382.jpg
-------
s16383.jpg
-------
s16384.jpg
-------
s163

-------
s15207.jpg
-------
s15208.jpg
-------
s15205.jpg
-------
s15206.jpg
-------
s15205.jpg
-------
s15206.jpg
-------
s15205.jpg
-------
s15206.jpg
-------
s15205.jpg
-------
s15206.jpg
-------
s15209.jpg
-------
s15210.jpg
-------
s15211.jpg
-------
s15212.jpg
-------
s15211.jpg
-------
s15212.jpg
-------
s15211.jpg
-------
s15212.jpg
-------
s15213.jpg
-------
s15214.jpg
-------
s15213.jpg
-------
s15214.jpg
-------
s15215.jpg
-------
s15216.jpg
-------
s15217.jpg
-------
s15218.jpg
-------
s15219.jpg
-------
s15220.jpg
-------
s15221.jpg
-------
s15222.jpg
-------
s15223.jpg
-------
s15224.jpg
-------
s15225.jpg
-------
s15224.jpg
-------
s15225.jpg
-------
s15224.jpg
-------
s15225.jpg
-------
s15226.jpg
-------
s15227.jpg
-------
s15228.jpg
-------
s15229.jpg
-------
s15228.jpg
-------
s15229.jpg
-------
s15228.jpg
-------
s15229.jpg
-------
s15228.jpg
-------
s15229.jpg
-------
s15228.jpg
-------
s15229.jpg
-------
s15228.jpg
-------
s15229.jpg
-------
s15228.jpg
-------
s152

s14360.jpg
-------
s14361.jpg
-------
s14362.jpg
-------
s14363.jpg
-------
s14364.jpg
-------
s14365.jpg
-------
s14366.jpg
-------
s14367.jpg
-------
s14368.jpg
-------
s14369.jpg
-------
s14365.jpg
-------
s14366.jpg
-------
s14370.jpg
-------
s14371.jpg
-------
s14372.jpg
-------
s14366.jpg
-------
s14365.jpg
-------
s14370.jpg
-------
s14373.jpg
-------
s14374.jpg
-------
s14373.jpg
-------
s14374.jpg
-------
s14376.jpg
-------
s14377.jpg
-------
s14378.jpg
-------
s14379.jpg
-------
s14380.jpg
-------
s14381.jpg
-------
s14348.jpg
-------
s14349.jpg
-------
s14380.jpg
-------
s14379.jpg
-------
s14382.jpg
-------
s14347.jpg
-------
s14381.jpg
-------
s14367.jpg
-------
s14369.jpg
-------
s14348.jpg
-------
s14349.jpg
-------
s14368.jpg
-------
s14383.jpg
-------
s14384.jpg
-------
s14384.jpg
-------
s14383.jpg
-------
s14351.jpg
-------
s14350.jpg
-------
s14367.jpg
-------
s14369.jpg
-------
s14371.jpg
-------
s14372.jpg
-------
s14385.jpg
-------
s14386.jpg
-------
s14385.jpg
-

s14562.jpg
-------
s14563.jpg
-------
s14564.jpg
-------
s14565.jpg
-------
s14566.jpg
-------
s14567.jpg
-------
s14562.jpg
-------
s14564.jpg
-------
s14565.jpg
-------
s14564.jpg
-------
s14565.jpg
-------
s14568.jpg
-------
s14569.jpg
-------
s14570.jpg
-------
s14571.jpg
-------
s14572.jpg
-------
s14573.jpg
-------
s14574.jpg
-------
s14575.jpg
-------
s14576.jpg
-------
s14577.jpg
-------
s14578.jpg
-------
s14579.jpg
-------
s14580.jpg
-------
s14581.jpg
-------
s14578.jpg
-------
s14579.jpg
-------
s14580.jpg
-------
s14582.jpg
-------
s14581.jpg
-------
s14583.jpg
-------
s14584.jpg
-------
s14585.jpg
-------
s14586.jpg
-------
s14587.jpg
-------
s14586.jpg
-------
s14587.jpg
-------
s14588.jpg
-------
s14589.jpg
-------
s14590.jpg
-------
s14591.jpg
-------
s14592.jpg
-------
s14583.jpg
-------
s14584.jpg
-------
s14593.jpg
-------
s14594.jpg
-------
s14595.jpg
-------
s14593.jpg
-------
s14594.jpg
-------
s14595.jpg
-------
s14593.jpg
-------
s14594.jpg
-------
s14595.jpg
-

s15643.jpg
-------
s14310.jpg
-------
s14311.jpg
-------
s14312.jpg
-------
s14313.jpg
-------
s14314.jpg
-------
s14315.jpg
-------
s14316.jpg
-------
s14317.jpg
-------
s14318.jpg
-------
s14316.jpg
-------
s14319.jpg
-------
s14319.jpg
-------
s14320.jpg
-------
s14321.jpg
-------
s14322.jpg
-------
s14318.jpg
-------
s14323.jpg
-------
s14324.jpg
-------
s14323.jpg
-------
s14324.jpg
-------
s14323.jpg
-------
s14324.jpg
-------
s14323.jpg
-------
s14324.jpg
-------
s14323.jpg
-------
s14324.jpg
-------
s14325.jpg
-------
s14326.jpg
-------
s14325.jpg
-------
s14326.jpg
-------
s14325.jpg
-------
s14326.jpg
-------
s14325.jpg
-------
s14326.jpg
-------
s14317.jpg
-------
s14327.jpg
-------
s14328.jpg
-------
s14317.jpg
-------
s14327.jpg
-------
s14328.jpg
-------
s14329.jpg
-------
s14330.jpg
-------
s14331.jpg
-------
s15545.jpg
-------
s15546.jpg
-------
s15547.jpg
-------
s15545.jpg
-------
s15546.jpg
-------
s15547.jpg
-------
s15548.jpg
-------
s15549.jpg
-------
s15550.jpg
-

-------
s12767.jpg
-------
s12771.jpg
-------
s12770.jpg
-------
s12767.jpg
-------
s12770.jpg
-------
s12767.jpg
-------
s12772.jpg
-------
s12773.jpg
-------
s12774.jpg
-------
s12775.jpg
-------
s12776.jpg
-------
s12777.jpg
-------
s12778.jpg
-------
s12779.jpg
-------
s12780.jpg
-------
s12781.jpg
-------
s12775.jpg
-------
s12776.jpg
-------
s12777.jpg
-------
s12778.jpg
-------
s12779.jpg
-------
s12780.jpg
-------
s12779.jpg
-------
s12780.jpg
-------
s12782.jpg
-------
s12783.jpg
-------
s12784.jpg
-------
s12785.jpg
-------
s12786.jpg
-------
s12785.jpg
-------
s12786.jpg
-------
s12774.jpg
-------
s12787.jpg
-------
s12788.jpg
-------
s12789.jpg
-------
s12790.jpg
-------
s12791.jpg
-------
s12787.jpg
-------
s12788.jpg
-------
s12787.jpg
-------
s12788.jpg
-------
s12789.jpg
-------
s12790.jpg
-------
s12791.jpg
-------
s12792.jpg
-------
s12793.jpg
-------
s12792.jpg
-------
s12793.jpg
-------
s16920.jpg
-------
s16921.jpg
-------
s16920.jpg
-------
s16921.jpg
-------
s169

-------
s15349.jpg
-------
s15350.jpg
-------
s15351.jpg
-------
s15352.jpg
-------
s15353.jpg
-------
s15354.jpg
-------
s15355.jpg
-------
s15356.jpg
-------
s15357.jpg
-------
s15358.jpg
-------
s15359.jpg
-------
s15355.jpg
-------
s15357.jpg
-------
s15358.jpg
-------
s15359.jpg
-------
s15360.jpg
-------
s15355.jpg
-------
s15357.jpg
-------
s15358.jpg
-------
s15355.jpg
-------
s15357.jpg
-------
s15359.jpg
-------
s15360.jpg
-------
s15355.jpg
-------
s15356.jpg
-------
s15360.jpg
-------
s15355.jpg
-------
s15356.jpg
-------
s15359.jpg
-------
s15360.jpg
-------
s15358.jpg
-------
s15359.jpg
-------
s15361.jpg
-------
s15362.jpg
-------
s15363.jpg
-------
s15364.jpg
-------
s15365.jpg
-------
s15366.jpg
-------
s15367.jpg
-------
s15365.jpg
-------
s15366.jpg
-------
s15367.jpg
-------
s15368.jpg
-------
s15369.jpg
-------
s15370.jpg
-------
s15371.jpg
-------
s15372.jpg
-------
s15373.jpg
-------
s15374.jpg
-------
s15375.jpg
-------
s15376.jpg
-------
s15377.jpg
-------
s153

In [130]:
import pickle
with open('data/pid_map_image.txt', 'rb') as f:
    u = pickle._Unpickler(f)
    u.encoding = 'latin1'
    data = u.load()

In [183]:
get_img_data('s9189.jpg')

[180, 252, 76, 203]
[233, 199, 83, 222]
[158, 261, 32, 110]


[[180, 252, 256, 455], [233, 199, 316, 421], [158, 261, 190, 371]]

In [185]:
import sys
import numpy as np
def get_img_data(img_name):
    bboxes = []
    for i in images['Img'][0]:
        if i[0][0] == img_name:
            for box in i[2]:
                for b in box:
                    bbox = list(b[0][0].astype(np.int64))
                    bbox[2], bbox[3] = bbox[0] + bbox[2], bbox[1] + bbox[3]
                    bboxes.append(bbox)
    return bboxes
                
d = data.copy()
print(d==data)
i = 0
for dd in d:
    sys.stdout.write('\r'+str(i)+'/'+str(len(d)))
    i+=1
    for dic in dd:
        bbox = get_img_data(dic['image'].split('/')[-1])
        #print(bbox)
        #print(dic['boxes'])
        #print(bbox == dic['boxes'])
        #print('-----')
        dic['boxes'] = bbox
print(d==data)

True
5531/5532True


In [186]:
with open('data/pid_map_image_update.txt', 'wb') as handle:
    pickle.dump(d, handle, protocol=pickle.HIGHEST_PROTOCOL)

In [129]:
node = [[] for _ in range(len(person['Person'][0]))]
for i,v in enumerate(person['Person'][0]):
    for j, nn in enumerate(v[2]):
        for n in nn:
            img_name = '/home/workspace/keras-person-search/data/psdb/dataset/Image/SSM/' + str(n[0][0])
            new_img = True
            bbox = list(n[1][0])
            bbox[2],bbox[3] = bbox[0] + bbox[2], bbox[1] + bbox[3]
            for d in node[i]:
                if d['image'] == img_name:
                    d['boxes'].append(bbox)
                    d['gt_pids'].append(i)
                    new_img = False
                    break
            if new_img:
                node[i].append({'image':img_name, 'boxes':[bbox], 'gt_pids':[i]})
        #box = n[0][1][0]
#     node[i]['boxes'] = v[2][0][1][1][0]
#     node[i]['image'] = '/home/workspace/keras-person-search/data/psdb/dataset/Image/SSM/' + str(v[2][0][1][0][0])
node[100]

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in ubyte_scalars
  


[{'boxes': [[380, 255, 478, 493]],
  'gt_pids': [100],
  'image': '/home/workspace/keras-person-search/data/psdb/dataset/Image/SSM/s197.jpg'},
 {'boxes': [[351, 326, 441, 552]],
  'gt_pids': [100],
  'image': '/home/workspace/keras-person-search/data/psdb/dataset/Image/SSM/s198.jpg'}]